import { useEffect, useMemo, useState } from 'react'
import { Alert, Avatar, Box, Button, Card, CardContent, CircularProgress, Dialog, DialogActions, DialogContent, DialogTitle, Stack, TextField, Typography } from '@mui/material'
import { AddPhotoAlternateRounded, AddRounded, LocationOnRounded } from '@mui/icons-material'
import { collection, onSnapshot, orderBy, query } from 'firebase/firestore'
import { db } from '../firebase'
import { createAcademy, updateAcademyBranding } from '../services/managementService'
import { useI18n } from '../i18n'
import { matchesSearch } from '../utils/search'

interface Academy { id: string; name: string; city: string; country: string; status: string; logoUrl?: string }
export function Academies({ notify, searchQuery = '' }: { notify: (message: string) => void; searchQuery?: string }) {
  const { t } = useI18n(); const [rows, setRows] = useState<Academy[]>([]); const [open, setOpen] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [name, setName] = useState(''); const [city, setCity] = useState('Douala'); const [country, setCountry] = useState('Cameroun')
  const [brandingAcademy, setBrandingAcademy] = useState<Academy | null>(null); const [logoDataUrl, setLogoDataUrl] = useState('')
  useEffect(() => onSnapshot(query(collection(db, 'academies'), orderBy('name')), snap => setRows(snap.docs.map(item => ({ id: item.id, ...item.data() } as Academy)))), [])
  const submit = async () => { setLoading(true); setError(''); try { await createAcademy({ name, city, country }); notify(t('Académie créée')); setOpen(false); setName('') } catch (reason) { setError(reason instanceof Error ? t(reason.message) : t('Une erreur est survenue')) } finally { setLoading(false) } }
  const chooseLogo = (file?: File) => { if (!file) return; if (!['image/jpeg', 'image/png', 'image/webp'].includes(file.type) || file.size > 2_000_000) { setError(t('Le logo doit être une image PNG, JPEG ou WebP de 2 Mo maximum.')); return } const reader = new FileReader(); reader.onload = () => setLogoDataUrl(String(reader.result)); reader.readAsDataURL(file) }
  const saveBranding = async () => { if (!brandingAcademy || !logoDataUrl) return; setLoading(true); setError(''); try { await updateAcademyBranding({ academyId: brandingAcademy.id, logoDataUrl }); notify(t('Logo de l’académie mis à jour')); setBrandingAcademy(null); setLogoDataUrl('') } catch (reason) { setError(reason instanceof Error ? t(reason.message) : t('Une erreur est survenue')) } finally { setLoading(false) } }
  const visibleRows = useMemo(() => rows.filter(row => matchesSearch(searchQuery, row.id, row.name, row.city, row.country, row.status)), [rows, searchQuery])
  return <Stack gap={2.5}><Card><CardContent><Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" alignItems={{ sm: 'center' }} gap={2}><Box><Typography variant="h5">{t('Académies')}</Typography><Typography color="text.secondary">{t('Gérez les clubs et centres de formation du réseau.')}</Typography></Box><Button variant="contained" startIcon={<AddRounded />} onClick={() => setOpen(true)}>{t('Nouvelle académie')}</Button></Stack></CardContent></Card>
    <Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', md: 'repeat(2,1fr)', xl: 'repeat(3,1fr)' }, gap: 2 }}>{visibleRows.map(row => <Card key={row.id}><CardContent><Avatar variant="rounded" src={row.logoUrl || '/challengeme-academy-logo.jpg'} alt={row.name} sx={{ width: 76, height: 76, bgcolor: 'white' }} /><Typography variant="h6" mt={2}>{row.name}</Typography><Stack direction="row" gap={.7} alignItems="center" color="text.secondary"><LocationOnRounded fontSize="small"/><Typography variant="body2">{row.city}, {row.country}</Typography></Stack><Typography variant="caption" color="text.secondary">{t('ID')}: {row.id}</Typography><Button fullWidth variant="outlined" startIcon={<AddPhotoAlternateRounded />} sx={{ mt: 2 }} onClick={() => { setError(''); setLogoDataUrl(''); setBrandingAcademy(row) }}>{t('Modifier le logo')}</Button></CardContent></Card>)}</Box>
    <Dialog open={open} onClose={() => setOpen(false)} fullWidth maxWidth="sm"><DialogTitle>{t('Nouvelle académie')}</DialogTitle><DialogContent><Stack gap={2} pt={1}>{error && <Alert severity="error">{error}</Alert>}<TextField label={t('Nom')} value={name} onChange={e => setName(e.target.value)} /><TextField label={t('Ville')} value={city} onChange={e => setCity(e.target.value)} /><TextField label={t('Pays')} value={country} onChange={e => setCountry(e.target.value)} /></Stack></DialogContent><DialogActions sx={{ p: 3 }}><Button onClick={() => setOpen(false)}>{t('Annuler')}</Button><Button variant="contained" disabled={loading || !name || !city} onClick={submit}>{loading ? <CircularProgress size={20} /> : t('Créer')}</Button></DialogActions></Dialog>
    <Dialog open={Boolean(brandingAcademy)} onClose={() => !loading && setBrandingAcademy(null)} fullWidth maxWidth="sm"><DialogTitle>{t('Modifier le logo')} · {brandingAcademy?.name}</DialogTitle><DialogContent><Stack gap={2} pt={1}>{error && <Alert severity="error">{error}</Alert>}<Box component="img" src={logoDataUrl || brandingAcademy?.logoUrl || '/challengeme-academy-logo.jpg'} alt={brandingAcademy?.name} sx={{ width: 180, height: 180, objectFit: 'contain', alignSelf: 'center', borderRadius: 3 }} /><Button component="label" variant="outlined" startIcon={<AddPhotoAlternateRounded />}>{t('Choisir une image')}<input hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={event => chooseLogo(event.target.files?.[0])} /></Button><Typography variant="caption" color="text.secondary">{t('PNG, JPEG ou WebP, 2 Mo maximum.')}</Typography></Stack></DialogContent><DialogActions sx={{ p: 3 }}><Button onClick={() => setBrandingAcademy(null)} disabled={loading}>{t('Annuler')}</Button><Button variant="contained" disabled={loading || !logoDataUrl} onClick={saveBranding}>{loading ? <CircularProgress size={20} /> : t('Enregistrer')}</Button></DialogActions></Dialog>
  </Stack>
}
