-- Sport Connect Academy — local greenfield foundation, phase 3A.
CREATE TABLE public.service_offers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  academy_id uuid NOT NULL,
  UNIQUE (academy_id, id),
  created_at timestamptz NOT NULL DEFAULT transaction_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT transaction_timestamp(),
  created_by uuid,
  updated_by uuid,
  offer_key uuid NOT NULL,
  version integer NOT NULL CHECK (version > 0),
  supersedes_id uuid,
  name text NOT NULL CHECK (length(btrim(name)) BETWEEN 1 AND 160),
  activity text NOT NULL CHECK (activity IN ('TENNIS', 'PADEL')),
  session_type text NOT NULL CHECK (session_type IN ('PRIVATE', 'SEMI_PRIVATE', 'GROUP')),
  min_age integer NOT NULL CHECK (min_age BETWEEN 2 AND 100),
  max_age integer NOT NULL CHECK (max_age BETWEEN 2 AND 100),
  session_count integer NOT NULL CHECK (session_count BETWEEN 1 AND 1000),
  price numeric(18,2) NOT NULL,
  currency text NOT NULL CHECK (currency IN ('AED', 'XAF', 'EUR', 'USD', 'MAD')),
  CHECK (price >= 0 AND price <> 'NaN'::numeric),
  CHECK (currency <> 'XAF' OR price = trunc(price)),
  price_basis text NOT NULL CHECK (price_basis IN ('PACKAGE', 'SESSION')),
  duration_minutes integer CHECK (duration_minutes BETWEEN 15 AND 480),
  status text NOT NULL CHECK (status IN ('DRAFT', 'PUBLISHED', 'RETIRED')),
  published_at timestamptz,
  retired_at timestamptz,
  UNIQUE (academy_id, offer_key, version),
  UNIQUE (academy_id, offer_key, id),
  CHECK (min_age <= max_age),
  CHECK (supersedes_id IS NULL OR supersedes_id <> id)
);

CREATE UNIQUE INDEX service_offers_current_publication ON public.service_offers (academy_id, offer_key) WHERE status = 'PUBLISHED';
CREATE TABLE public.player_packages (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  academy_id uuid NOT NULL,
  UNIQUE (academy_id, id),
  created_at timestamptz NOT NULL DEFAULT transaction_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT transaction_timestamp(),
  created_by uuid,
  updated_by uuid,
  player_id uuid NOT NULL,
  service_offer_id uuid NOT NULL,
  purchased_sessions integer NOT NULL CHECK (purchased_sessions >= 0),
  remaining_sessions integer NOT NULL DEFAULT 0 CHECK (remaining_sessions >= 0),
  total_price numeric(18,2) NOT NULL,
  currency text NOT NULL CHECK (currency IN ('AED', 'XAF', 'EUR', 'USD', 'MAD')),
  CHECK (total_price >= 0 AND total_price <> 'NaN'::numeric),
  CHECK (currency <> 'XAF' OR total_price = trunc(total_price)),
  payment_state text NOT NULL CHECK (payment_state IN ('PENDING', 'CONFIRMED')),
  acquired_at timestamptz,
  status text NOT NULL CHECK (status IN ('PENDING', 'ACTIVE', 'EXHAUSTED', 'ARCHIVED')),
  terms_snapshot jsonb NOT NULL CHECK (jsonb_typeof(terms_snapshot) = 'object' AND octet_length(terms_snapshot::text) <= 65536),
  origin text NOT NULL CHECK (origin IN ('PURCHASE')),
  UNIQUE (academy_id, player_id, id)
);

CREATE TABLE private.course_ledger (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  academy_id uuid NOT NULL,
  UNIQUE (academy_id, id),
  created_at timestamptz NOT NULL DEFAULT transaction_timestamp(),
  operation_id uuid NOT NULL,
  effect_key text NOT NULL CHECK (length(btrim(effect_key)) > 0),
  UNIQUE (operation_id, effect_key),
  actor_kind text NOT NULL CHECK (actor_kind IN ('USER','SYSTEM')),
  actor_user_id uuid,
  actor_ref text NOT NULL CHECK (length(btrim(actor_ref)) > 0),
  CHECK ((actor_kind = 'USER' AND actor_user_id IS NOT NULL AND actor_ref = actor_user_id::text) OR (actor_kind = 'SYSTEM' AND actor_user_id IS NULL)),
  package_id uuid NOT NULL,
  booking_id uuid,
  delta integer NOT NULL CHECK (delta <> 0),
  reason text NOT NULL CHECK (reason IN ('PACKAGE_PURCHASE', 'SESSION_CONSUMED', 'BOOKING_CANCELLATION_CORRECTION', 'ATTENDANCE_CORRECTION', 'MANUAL_ADJUSTMENT', 'ADMIN_CORRECTION')),
  occurred_at timestamptz NOT NULL,
  reason_text text,
  reverses_entry_id uuid UNIQUE,
  UNIQUE (academy_id, package_id, id),
  CHECK (reason <> 'PACKAGE_PURCHASE' OR delta > 0),
  CHECK (reason <> 'SESSION_CONSUMED' OR (delta = -1 AND booking_id IS NOT NULL)),
  CHECK (reason NOT IN ('BOOKING_CANCELLATION_CORRECTION','ATTENDANCE_CORRECTION') OR (delta = 1 AND booking_id IS NOT NULL AND reverses_entry_id IS NOT NULL)),
  CHECK (reason NOT IN ('MANUAL_ADJUSTMENT','ADMIN_CORRECTION') OR (reason_text IS NOT NULL AND length(btrim(reason_text)) BETWEEN 1 AND 1000)),
  CHECK (reverses_entry_id IS NULL OR reverses_entry_id <> id)
);
