-- Sport Connect Academy — local greenfield foundation, phase 3A.
-- Fixed catalog only. Permissions never bypass relation/scope checks in future RPC/RLS.
INSERT INTO public.permissions (code, description) VALUES
  ('academies.create', 'Action academies.create'),
  ('academies.read_metadata', 'Action academies.read_metadata'),
  ('academies.set_status', 'Action academies.set_status'),
  ('academy.branding_upload', 'Action academy.branding_upload'),
  ('academy.notification_recipients_write', 'Action academy.notification_recipients_write'),
  ('academy.read', 'Action academy.read'),
  ('academy.update', 'Action academy.update'),
  ('attendance.correct', 'Action attendance.correct'),
  ('attendance.read', 'Action attendance.read'),
  ('attendance.record', 'Action attendance.record'),
  ('audit.read', 'Action audit.read'),
  ('bookings.approve', 'Action bookings.approve'),
  ('bookings.archive', 'Action bookings.archive'),
  ('bookings.cancel', 'Action bookings.cancel'),
  ('bookings.complete', 'Action bookings.complete'),
  ('bookings.override.age', 'Action bookings.override.age'),
  ('bookings.override.capacity', 'Action bookings.override.capacity'),
  ('bookings.override.offer', 'Action bookings.override.offer'),
  ('bookings.override.player_overlap', 'Action bookings.override.player_overlap'),
  ('bookings.override.quota', 'Action bookings.override.quota'),
  ('bookings.read', 'Action bookings.read'),
  ('bookings.reject', 'Action bookings.reject'),
  ('bookings.request', 'Action bookings.request'),
  ('bookings.schedule', 'Action bookings.schedule'),
  ('coaches.archive', 'Action coaches.archive'),
  ('coaches.create', 'Action coaches.create'),
  ('coaches.read', 'Action coaches.read'),
  ('communities.archive', 'Action communities.archive'),
  ('communities.create', 'Action communities.create'),
  ('communities.read', 'Action communities.read'),
  ('communities.update', 'Action communities.update'),
  ('community_courses.archive', 'Action community_courses.archive'),
  ('community_courses.create', 'Action community_courses.create'),
  ('community_courses.read', 'Action community_courses.read'),
  ('community_courses.update', 'Action community_courses.update'),
  ('course_ledger.adjust', 'Action course_ledger.adjust'),
  ('course_ledger.read', 'Action course_ledger.read'),
  ('courts.archive', 'Action courts.archive'),
  ('courts.create', 'Action courts.create'),
  ('courts.read', 'Action courts.read'),
  ('courts.update', 'Action courts.update'),
  ('evaluations.correct', 'Action evaluations.correct'),
  ('evaluations.read', 'Action evaluations.read'),
  ('evaluations.record', 'Action evaluations.record'),
  ('invoices.issue', 'Action invoices.issue'),
  ('invoices.read', 'Action invoices.read'),
  ('memberships.invite', 'Action memberships.invite'),
  ('memberships.read', 'Action memberships.read'),
  ('memberships.set_roles', 'Action memberships.set_roles'),
  ('memberships.suspend', 'Action memberships.suspend'),
  ('memberships.transfer_owner', 'Action memberships.transfer_owner'),
  ('notifications.read_metadata', 'Action notifications.read_metadata'),
  ('notifications.retry', 'Action notifications.retry'),
  ('packages.activate_credit', 'Action packages.activate_credit'),
  ('packages.archive', 'Action packages.archive'),
  ('packages.purchase', 'Action packages.purchase'),
  ('packages.read', 'Action packages.read'),
  ('payments.confirm', 'Action payments.confirm'),
  ('payments.read', 'Action payments.read'),
  ('payments.record', 'Action payments.record'),
  ('plans.read', 'Action plans.read'),
  ('plans.write', 'Action plans.write'),
  ('platform_roles.assign', 'Action platform_roles.assign'),
  ('platform_roles.read', 'Action platform_roles.read'),
  ('player_links.assign', 'Action player_links.assign'),
  ('player_links.read', 'Action player_links.read'),
  ('player_links.revoke', 'Action player_links.revoke'),
  ('player_links.set_contacts', 'Action player_links.set_contacts'),
  ('players.archive', 'Action players.archive'),
  ('players.create', 'Action players.create'),
  ('players.read', 'Action players.read'),
  ('players.update_identity', 'Action players.update_identity'),
  ('service_offers.create', 'Action service_offers.create'),
  ('service_offers.publish', 'Action service_offers.publish'),
  ('service_offers.read', 'Action service_offers.read'),
  ('service_offers.retire', 'Action service_offers.retire'),
  ('sessions.cancel', 'Action sessions.cancel'),
  ('sessions.close', 'Action sessions.close'),
  ('sessions.create', 'Action sessions.create'),
  ('sessions.read', 'Action sessions.read'),
  ('stadiums.archive', 'Action stadiums.archive'),
  ('stadiums.create', 'Action stadiums.create'),
  ('stadiums.read', 'Action stadiums.read'),
  ('stadiums.update', 'Action stadiums.update'),
  ('subscriptions.read', 'Action subscriptions.read'),
  ('subscriptions.transition', 'Action subscriptions.transition'),
  ('tournaments.archive', 'Action tournaments.archive'),
  ('tournaments.cover_upload', 'Action tournaments.cover_upload'),
  ('tournaments.create', 'Action tournaments.create'),
  ('tournaments.read', 'Action tournaments.read'),
  ('tournaments.update', 'Action tournaments.update');

INSERT INTO public.platform_roles (code, description) VALUES ('SUPER_ADMIN', 'Administration des rôles et de la plateforme'), ('PLATFORM_ADMIN', 'Gestion SaaS sans accès métier implicite');
INSERT INTO public.academy_roles (code, description) VALUES
  ('ACADEMY_OWNER', 'Bundle fixe ACADEMY_OWNER'),
  ('ACADEMY_ADMIN', 'Bundle fixe ACADEMY_ADMIN'),
  ('MANAGER', 'Bundle fixe MANAGER'),
  ('STAFF', 'Bundle fixe STAFF'),
  ('COACH', 'Bundle fixe COACH'),
  ('STUDENT', 'Bundle fixe STUDENT'),
  ('PARENT', 'Bundle fixe PARENT');

INSERT INTO private.platform_role_permissions (role_code, permission_code) VALUES
  ('SUPER_ADMIN', 'platform_roles.read'),
  ('SUPER_ADMIN', 'platform_roles.assign'),
  ('SUPER_ADMIN', 'academies.create'),
  ('SUPER_ADMIN', 'academies.read_metadata'),
  ('SUPER_ADMIN', 'academies.set_status'),
  ('SUPER_ADMIN', 'plans.read'),
  ('SUPER_ADMIN', 'plans.write'),
  ('SUPER_ADMIN', 'subscriptions.read'),
  ('SUPER_ADMIN', 'subscriptions.transition'),
  ('SUPER_ADMIN', 'audit.read'),
  ('PLATFORM_ADMIN', 'academies.create'),
  ('PLATFORM_ADMIN', 'academies.read_metadata'),
  ('PLATFORM_ADMIN', 'academies.set_status'),
  ('PLATFORM_ADMIN', 'plans.read'),
  ('PLATFORM_ADMIN', 'plans.write'),
  ('PLATFORM_ADMIN', 'subscriptions.read'),
  ('PLATFORM_ADMIN', 'subscriptions.transition'),
  ('PLATFORM_ADMIN', 'audit.read');

INSERT INTO private.academy_role_permissions (role_code, permission_code) VALUES
  ('ACADEMY_OWNER', 'academy.branding_upload'),
  ('ACADEMY_OWNER', 'academy.notification_recipients_write'),
  ('ACADEMY_OWNER', 'academy.read'),
  ('ACADEMY_OWNER', 'academy.update'),
  ('ACADEMY_OWNER', 'attendance.correct'),
  ('ACADEMY_OWNER', 'attendance.read'),
  ('ACADEMY_OWNER', 'attendance.record'),
  ('ACADEMY_OWNER', 'audit.read'),
  ('ACADEMY_OWNER', 'bookings.approve'),
  ('ACADEMY_OWNER', 'bookings.archive'),
  ('ACADEMY_OWNER', 'bookings.cancel'),
  ('ACADEMY_OWNER', 'bookings.complete'),
  ('ACADEMY_OWNER', 'bookings.override.age'),
  ('ACADEMY_OWNER', 'bookings.override.capacity'),
  ('ACADEMY_OWNER', 'bookings.override.offer'),
  ('ACADEMY_OWNER', 'bookings.override.player_overlap'),
  ('ACADEMY_OWNER', 'bookings.override.quota'),
  ('ACADEMY_OWNER', 'bookings.read'),
  ('ACADEMY_OWNER', 'bookings.reject'),
  ('ACADEMY_OWNER', 'bookings.request'),
  ('ACADEMY_OWNER', 'bookings.schedule'),
  ('ACADEMY_OWNER', 'coaches.archive'),
  ('ACADEMY_OWNER', 'coaches.create'),
  ('ACADEMY_OWNER', 'coaches.read'),
  ('ACADEMY_OWNER', 'communities.archive'),
  ('ACADEMY_OWNER', 'communities.create'),
  ('ACADEMY_OWNER', 'communities.read'),
  ('ACADEMY_OWNER', 'communities.update'),
  ('ACADEMY_OWNER', 'community_courses.archive'),
  ('ACADEMY_OWNER', 'community_courses.create'),
  ('ACADEMY_OWNER', 'community_courses.read'),
  ('ACADEMY_OWNER', 'community_courses.update'),
  ('ACADEMY_OWNER', 'course_ledger.adjust'),
  ('ACADEMY_OWNER', 'course_ledger.read'),
  ('ACADEMY_OWNER', 'courts.archive'),
  ('ACADEMY_OWNER', 'courts.create'),
  ('ACADEMY_OWNER', 'courts.read'),
  ('ACADEMY_OWNER', 'courts.update'),
  ('ACADEMY_OWNER', 'evaluations.correct'),
  ('ACADEMY_OWNER', 'evaluations.read'),
  ('ACADEMY_OWNER', 'evaluations.record'),
  ('ACADEMY_OWNER', 'invoices.issue'),
  ('ACADEMY_OWNER', 'invoices.read'),
  ('ACADEMY_OWNER', 'memberships.invite'),
  ('ACADEMY_OWNER', 'memberships.read'),
  ('ACADEMY_OWNER', 'memberships.set_roles'),
  ('ACADEMY_OWNER', 'memberships.suspend'),
  ('ACADEMY_OWNER', 'memberships.transfer_owner'),
  ('ACADEMY_OWNER', 'notifications.read_metadata'),
  ('ACADEMY_OWNER', 'notifications.retry'),
  ('ACADEMY_OWNER', 'packages.activate_credit'),
  ('ACADEMY_OWNER', 'packages.archive'),
  ('ACADEMY_OWNER', 'packages.purchase'),
  ('ACADEMY_OWNER', 'packages.read'),
  ('ACADEMY_OWNER', 'payments.confirm'),
  ('ACADEMY_OWNER', 'payments.read'),
  ('ACADEMY_OWNER', 'payments.record'),
  ('ACADEMY_OWNER', 'player_links.assign'),
  ('ACADEMY_OWNER', 'player_links.read'),
  ('ACADEMY_OWNER', 'player_links.revoke'),
  ('ACADEMY_OWNER', 'player_links.set_contacts'),
  ('ACADEMY_OWNER', 'players.archive'),
  ('ACADEMY_OWNER', 'players.create'),
  ('ACADEMY_OWNER', 'players.read'),
  ('ACADEMY_OWNER', 'players.update_identity'),
  ('ACADEMY_OWNER', 'service_offers.create'),
  ('ACADEMY_OWNER', 'service_offers.publish'),
  ('ACADEMY_OWNER', 'service_offers.read'),
  ('ACADEMY_OWNER', 'service_offers.retire'),
  ('ACADEMY_OWNER', 'sessions.cancel'),
  ('ACADEMY_OWNER', 'sessions.close'),
  ('ACADEMY_OWNER', 'sessions.create'),
  ('ACADEMY_OWNER', 'sessions.read'),
  ('ACADEMY_OWNER', 'stadiums.archive'),
  ('ACADEMY_OWNER', 'stadiums.create'),
  ('ACADEMY_OWNER', 'stadiums.read'),
  ('ACADEMY_OWNER', 'stadiums.update'),
  ('ACADEMY_OWNER', 'subscriptions.read'),
  ('ACADEMY_OWNER', 'tournaments.archive'),
  ('ACADEMY_OWNER', 'tournaments.cover_upload'),
  ('ACADEMY_OWNER', 'tournaments.create'),
  ('ACADEMY_OWNER', 'tournaments.read'),
  ('ACADEMY_OWNER', 'tournaments.update'),
  ('ACADEMY_ADMIN', 'academy.branding_upload'),
  ('ACADEMY_ADMIN', 'academy.notification_recipients_write'),
  ('ACADEMY_ADMIN', 'academy.read'),
  ('ACADEMY_ADMIN', 'academy.update'),
  ('ACADEMY_ADMIN', 'attendance.correct'),
  ('ACADEMY_ADMIN', 'attendance.read'),
  ('ACADEMY_ADMIN', 'attendance.record'),
  ('ACADEMY_ADMIN', 'audit.read'),
  ('ACADEMY_ADMIN', 'bookings.approve'),
  ('ACADEMY_ADMIN', 'bookings.archive'),
  ('ACADEMY_ADMIN', 'bookings.cancel'),
  ('ACADEMY_ADMIN', 'bookings.complete'),
  ('ACADEMY_ADMIN', 'bookings.override.age'),
  ('ACADEMY_ADMIN', 'bookings.override.capacity'),
  ('ACADEMY_ADMIN', 'bookings.override.offer'),
  ('ACADEMY_ADMIN', 'bookings.override.player_overlap'),
  ('ACADEMY_ADMIN', 'bookings.override.quota'),
  ('ACADEMY_ADMIN', 'bookings.read'),
  ('ACADEMY_ADMIN', 'bookings.reject'),
  ('ACADEMY_ADMIN', 'bookings.request'),
  ('ACADEMY_ADMIN', 'bookings.schedule'),
  ('ACADEMY_ADMIN', 'coaches.archive'),
  ('ACADEMY_ADMIN', 'coaches.create'),
  ('ACADEMY_ADMIN', 'coaches.read'),
  ('ACADEMY_ADMIN', 'communities.archive'),
  ('ACADEMY_ADMIN', 'communities.create'),
  ('ACADEMY_ADMIN', 'communities.read'),
  ('ACADEMY_ADMIN', 'communities.update'),
  ('ACADEMY_ADMIN', 'community_courses.archive'),
  ('ACADEMY_ADMIN', 'community_courses.create'),
  ('ACADEMY_ADMIN', 'community_courses.read'),
  ('ACADEMY_ADMIN', 'community_courses.update'),
  ('ACADEMY_ADMIN', 'course_ledger.adjust'),
  ('ACADEMY_ADMIN', 'course_ledger.read'),
  ('ACADEMY_ADMIN', 'courts.archive'),
  ('ACADEMY_ADMIN', 'courts.create'),
  ('ACADEMY_ADMIN', 'courts.read'),
  ('ACADEMY_ADMIN', 'courts.update'),
  ('ACADEMY_ADMIN', 'evaluations.correct'),
  ('ACADEMY_ADMIN', 'evaluations.read'),
  ('ACADEMY_ADMIN', 'evaluations.record'),
  ('ACADEMY_ADMIN', 'invoices.issue'),
  ('ACADEMY_ADMIN', 'invoices.read'),
  ('ACADEMY_ADMIN', 'memberships.invite'),
  ('ACADEMY_ADMIN', 'memberships.read'),
  ('ACADEMY_ADMIN', 'memberships.set_roles'),
  ('ACADEMY_ADMIN', 'memberships.suspend'),
  ('ACADEMY_ADMIN', 'notifications.read_metadata'),
  ('ACADEMY_ADMIN', 'notifications.retry'),
  ('ACADEMY_ADMIN', 'packages.activate_credit'),
  ('ACADEMY_ADMIN', 'packages.archive'),
  ('ACADEMY_ADMIN', 'packages.purchase'),
  ('ACADEMY_ADMIN', 'packages.read'),
  ('ACADEMY_ADMIN', 'payments.confirm'),
  ('ACADEMY_ADMIN', 'payments.read'),
  ('ACADEMY_ADMIN', 'payments.record'),
  ('ACADEMY_ADMIN', 'player_links.assign'),
  ('ACADEMY_ADMIN', 'player_links.read'),
  ('ACADEMY_ADMIN', 'player_links.revoke'),
  ('ACADEMY_ADMIN', 'player_links.set_contacts'),
  ('ACADEMY_ADMIN', 'players.archive'),
  ('ACADEMY_ADMIN', 'players.create'),
  ('ACADEMY_ADMIN', 'players.read'),
  ('ACADEMY_ADMIN', 'players.update_identity'),
  ('ACADEMY_ADMIN', 'service_offers.create'),
  ('ACADEMY_ADMIN', 'service_offers.publish'),
  ('ACADEMY_ADMIN', 'service_offers.read'),
  ('ACADEMY_ADMIN', 'service_offers.retire'),
  ('ACADEMY_ADMIN', 'sessions.cancel'),
  ('ACADEMY_ADMIN', 'sessions.close'),
  ('ACADEMY_ADMIN', 'sessions.create'),
  ('ACADEMY_ADMIN', 'sessions.read'),
  ('ACADEMY_ADMIN', 'stadiums.archive'),
  ('ACADEMY_ADMIN', 'stadiums.create'),
  ('ACADEMY_ADMIN', 'stadiums.read'),
  ('ACADEMY_ADMIN', 'stadiums.update'),
  ('ACADEMY_ADMIN', 'subscriptions.read'),
  ('ACADEMY_ADMIN', 'tournaments.archive'),
  ('ACADEMY_ADMIN', 'tournaments.cover_upload'),
  ('ACADEMY_ADMIN', 'tournaments.create'),
  ('ACADEMY_ADMIN', 'tournaments.read'),
  ('ACADEMY_ADMIN', 'tournaments.update'),
  ('MANAGER', 'academy.read'),
  ('MANAGER', 'attendance.correct'),
  ('MANAGER', 'attendance.read'),
  ('MANAGER', 'bookings.approve'),
  ('MANAGER', 'bookings.archive'),
  ('MANAGER', 'bookings.cancel'),
  ('MANAGER', 'bookings.complete'),
  ('MANAGER', 'bookings.override.age'),
  ('MANAGER', 'bookings.override.capacity'),
  ('MANAGER', 'bookings.override.offer'),
  ('MANAGER', 'bookings.override.player_overlap'),
  ('MANAGER', 'bookings.override.quota'),
  ('MANAGER', 'bookings.read'),
  ('MANAGER', 'bookings.reject'),
  ('MANAGER', 'bookings.request'),
  ('MANAGER', 'bookings.schedule'),
  ('MANAGER', 'coaches.archive'),
  ('MANAGER', 'coaches.create'),
  ('MANAGER', 'coaches.read'),
  ('MANAGER', 'communities.archive'),
  ('MANAGER', 'communities.create'),
  ('MANAGER', 'communities.read'),
  ('MANAGER', 'communities.update'),
  ('MANAGER', 'community_courses.archive'),
  ('MANAGER', 'community_courses.create'),
  ('MANAGER', 'community_courses.read'),
  ('MANAGER', 'community_courses.update'),
  ('MANAGER', 'course_ledger.read'),
  ('MANAGER', 'courts.archive'),
  ('MANAGER', 'courts.create'),
  ('MANAGER', 'courts.read'),
  ('MANAGER', 'courts.update'),
  ('MANAGER', 'evaluations.correct'),
  ('MANAGER', 'evaluations.read'),
  ('MANAGER', 'memberships.read'),
  ('MANAGER', 'packages.read'),
  ('MANAGER', 'player_links.assign'),
  ('MANAGER', 'player_links.read'),
  ('MANAGER', 'player_links.revoke'),
  ('MANAGER', 'player_links.set_contacts'),
  ('MANAGER', 'players.archive'),
  ('MANAGER', 'players.create'),
  ('MANAGER', 'players.read'),
  ('MANAGER', 'players.update_identity'),
  ('MANAGER', 'service_offers.create'),
  ('MANAGER', 'service_offers.publish'),
  ('MANAGER', 'service_offers.read'),
  ('MANAGER', 'service_offers.retire'),
  ('MANAGER', 'sessions.cancel'),
  ('MANAGER', 'sessions.close'),
  ('MANAGER', 'sessions.create'),
  ('MANAGER', 'sessions.read'),
  ('MANAGER', 'stadiums.archive'),
  ('MANAGER', 'stadiums.create'),
  ('MANAGER', 'stadiums.read'),
  ('MANAGER', 'stadiums.update'),
  ('MANAGER', 'tournaments.archive'),
  ('MANAGER', 'tournaments.cover_upload'),
  ('MANAGER', 'tournaments.create'),
  ('MANAGER', 'tournaments.read'),
  ('MANAGER', 'tournaments.update'),
  ('STAFF', 'academy.read'),
  ('STAFF', 'attendance.read'),
  ('STAFF', 'bookings.approve'),
  ('STAFF', 'bookings.archive'),
  ('STAFF', 'bookings.cancel'),
  ('STAFF', 'bookings.complete'),
  ('STAFF', 'bookings.read'),
  ('STAFF', 'bookings.reject'),
  ('STAFF', 'bookings.schedule'),
  ('STAFF', 'coaches.read'),
  ('STAFF', 'communities.read'),
  ('STAFF', 'community_courses.read'),
  ('STAFF', 'courts.read'),
  ('STAFF', 'memberships.read'),
  ('STAFF', 'packages.read'),
  ('STAFF', 'player_links.read'),
  ('STAFF', 'players.read'),
  ('STAFF', 'service_offers.read'),
  ('STAFF', 'sessions.create'),
  ('STAFF', 'sessions.read'),
  ('STAFF', 'stadiums.read'),
  ('STAFF', 'tournaments.read'),
  ('COACH', 'academy.read'),
  ('COACH', 'attendance.correct'),
  ('COACH', 'attendance.read'),
  ('COACH', 'attendance.record'),
  ('COACH', 'bookings.read'),
  ('COACH', 'coaches.read'),
  ('COACH', 'evaluations.correct'),
  ('COACH', 'evaluations.read'),
  ('COACH', 'evaluations.record'),
  ('COACH', 'memberships.read'),
  ('COACH', 'players.read'),
  ('COACH', 'sessions.read'),
  ('STUDENT', 'academy.read'),
  ('STUDENT', 'attendance.read'),
  ('STUDENT', 'bookings.cancel'),
  ('STUDENT', 'bookings.read'),
  ('STUDENT', 'bookings.reject'),
  ('STUDENT', 'bookings.request'),
  ('STUDENT', 'coaches.read'),
  ('STUDENT', 'communities.read'),
  ('STUDENT', 'community_courses.read'),
  ('STUDENT', 'course_ledger.read'),
  ('STUDENT', 'courts.read'),
  ('STUDENT', 'evaluations.read'),
  ('STUDENT', 'invoices.read'),
  ('STUDENT', 'memberships.read'),
  ('STUDENT', 'packages.read'),
  ('STUDENT', 'payments.read'),
  ('STUDENT', 'player_links.read'),
  ('STUDENT', 'players.create'),
  ('STUDENT', 'players.read'),
  ('STUDENT', 'players.update_identity'),
  ('STUDENT', 'service_offers.read'),
  ('STUDENT', 'sessions.read'),
  ('STUDENT', 'stadiums.read'),
  ('STUDENT', 'tournaments.read'),
  ('PARENT', 'academy.read'),
  ('PARENT', 'attendance.read'),
  ('PARENT', 'bookings.cancel'),
  ('PARENT', 'bookings.read'),
  ('PARENT', 'bookings.reject'),
  ('PARENT', 'bookings.request'),
  ('PARENT', 'coaches.read'),
  ('PARENT', 'communities.read'),
  ('PARENT', 'community_courses.read'),
  ('PARENT', 'course_ledger.read'),
  ('PARENT', 'courts.read'),
  ('PARENT', 'evaluations.read'),
  ('PARENT', 'invoices.read'),
  ('PARENT', 'memberships.read'),
  ('PARENT', 'packages.read'),
  ('PARENT', 'payments.read'),
  ('PARENT', 'player_links.read'),
  ('PARENT', 'players.create'),
  ('PARENT', 'players.read'),
  ('PARENT', 'players.update_identity'),
  ('PARENT', 'service_offers.read'),
  ('PARENT', 'sessions.read'),
  ('PARENT', 'stadiums.read'),
  ('PARENT', 'tournaments.read');
