-- Sport Connect Academy — local greenfield foundation, phase 3A.
ALTER TABLE public.user_profiles ADD CONSTRAINT fk_user_profiles_1 FOREIGN KEY (id) REFERENCES auth.users (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE private.platform_user_roles ADD CONSTRAINT fk_platform_user_roles_2 FOREIGN KEY (user_id) REFERENCES public.user_profiles (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE private.platform_user_roles ADD CONSTRAINT fk_platform_user_roles_3 FOREIGN KEY (role_code) REFERENCES public.platform_roles (code) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE private.platform_user_roles ADD CONSTRAINT fk_platform_user_roles_4 FOREIGN KEY (granted_by) REFERENCES public.user_profiles (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE private.platform_user_roles ADD CONSTRAINT fk_platform_user_roles_5 FOREIGN KEY (revoked_by) REFERENCES public.user_profiles (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE private.platform_role_permissions ADD CONSTRAINT fk_platform_role_permissions_6 FOREIGN KEY (role_code) REFERENCES public.platform_roles (code) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE private.platform_role_permissions ADD CONSTRAINT fk_platform_role_permissions_7 FOREIGN KEY (permission_code) REFERENCES public.permissions (code) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.academies ADD CONSTRAINT fk_academies_8 FOREIGN KEY (created_by) REFERENCES public.user_profiles (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.academies ADD CONSTRAINT fk_academies_9 FOREIGN KEY (updated_by) REFERENCES public.user_profiles (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.academies ADD CONSTRAINT fk_academies_10 FOREIGN KEY (deleted_by) REFERENCES public.user_profiles (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.academies ADD CONSTRAINT fk_academies_11 FOREIGN KEY (id, logo_asset_id) REFERENCES private.academy_assets (academy_id, id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.academy_memberships ADD CONSTRAINT fk_academy_memberships_12 FOREIGN KEY (academy_id) REFERENCES public.academies (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.academy_memberships ADD CONSTRAINT fk_academy_memberships_13 FOREIGN KEY (created_by) REFERENCES public.user_profiles (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.academy_memberships ADD CONSTRAINT fk_academy_memberships_14 FOREIGN KEY (updated_by) REFERENCES public.user_profiles (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.academy_memberships ADD CONSTRAINT fk_academy_memberships_15 FOREIGN KEY (user_id) REFERENCES public.user_profiles (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE private.academy_membership_roles ADD CONSTRAINT fk_academy_membership_roles_16 FOREIGN KEY (academy_id) REFERENCES public.academies (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE private.academy_membership_roles ADD CONSTRAINT fk_academy_membership_roles_17 FOREIGN KEY (academy_id, membership_id) REFERENCES public.academy_memberships (academy_id, id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE private.academy_membership_roles ADD CONSTRAINT fk_academy_membership_roles_18 FOREIGN KEY (role_code) REFERENCES public.academy_roles (code) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE private.academy_membership_roles ADD CONSTRAINT fk_academy_membership_roles_19 FOREIGN KEY (granted_by) REFERENCES public.user_profiles (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE private.academy_membership_roles ADD CONSTRAINT fk_academy_membership_roles_20 FOREIGN KEY (revoked_by) REFERENCES public.user_profiles (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE private.academy_role_permissions ADD CONSTRAINT fk_academy_role_permissions_21 FOREIGN KEY (role_code) REFERENCES public.academy_roles (code) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE private.academy_role_permissions ADD CONSTRAINT fk_academy_role_permissions_22 FOREIGN KEY (permission_code) REFERENCES public.permissions (code) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE private.academy_invitations ADD CONSTRAINT fk_academy_invitations_23 FOREIGN KEY (academy_id) REFERENCES public.academies (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE private.academy_invitations ADD CONSTRAINT fk_academy_invitations_24 FOREIGN KEY (invited_user_id) REFERENCES public.user_profiles (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE private.academy_invitations ADD CONSTRAINT fk_academy_invitations_25 FOREIGN KEY (academy_id, membership_id) REFERENCES public.academy_memberships (academy_id, id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE private.academy_invitations ADD CONSTRAINT fk_academy_invitations_26 FOREIGN KEY (requested_by) REFERENCES public.user_profiles (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE private.academy_invitations ADD CONSTRAINT fk_academy_invitations_27 FOREIGN KEY (operation_id) REFERENCES private.command_receipts (id) ON UPDATE RESTRICT ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.communities ADD CONSTRAINT fk_communities_28 FOREIGN KEY (academy_id) REFERENCES public.academies (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.communities ADD CONSTRAINT fk_communities_29 FOREIGN KEY (created_by) REFERENCES public.user_profiles (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.communities ADD CONSTRAINT fk_communities_30 FOREIGN KEY (updated_by) REFERENCES public.user_profiles (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.communities ADD CONSTRAINT fk_communities_31 FOREIGN KEY (deleted_by) REFERENCES public.user_profiles (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.community_courses ADD CONSTRAINT fk_community_courses_32 FOREIGN KEY (academy_id) REFERENCES public.academies (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.community_courses ADD CONSTRAINT fk_community_courses_33 FOREIGN KEY (created_by) REFERENCES public.user_profiles (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.community_courses ADD CONSTRAINT fk_community_courses_34 FOREIGN KEY (updated_by) REFERENCES public.user_profiles (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.community_courses ADD CONSTRAINT fk_community_courses_35 FOREIGN KEY (deleted_by) REFERENCES public.user_profiles (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.community_courses ADD CONSTRAINT fk_community_courses_36 FOREIGN KEY (academy_id, community_id) REFERENCES public.communities (academy_id, id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.players ADD CONSTRAINT fk_players_37 FOREIGN KEY (academy_id) REFERENCES public.academies (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.players ADD CONSTRAINT fk_players_38 FOREIGN KEY (created_by) REFERENCES public.user_profiles (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.players ADD CONSTRAINT fk_players_39 FOREIGN KEY (updated_by) REFERENCES public.user_profiles (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.players ADD CONSTRAINT fk_players_40 FOREIGN KEY (deleted_by) REFERENCES public.user_profiles (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.players ADD CONSTRAINT fk_players_41 FOREIGN KEY (academy_id, community_id) REFERENCES public.communities (academy_id, id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.player_links ADD CONSTRAINT fk_player_links_42 FOREIGN KEY (academy_id) REFERENCES public.academies (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.player_links ADD CONSTRAINT fk_player_links_43 FOREIGN KEY (academy_id, player_id) REFERENCES public.players (academy_id, id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.player_links ADD CONSTRAINT fk_player_links_44 FOREIGN KEY (user_id) REFERENCES public.user_profiles (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.player_links ADD CONSTRAINT fk_player_links_45 FOREIGN KEY (academy_id, user_id) REFERENCES public.academy_memberships (academy_id, user_id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.player_links ADD CONSTRAINT fk_player_links_46 FOREIGN KEY (assigned_by) REFERENCES public.user_profiles (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.player_links ADD CONSTRAINT fk_player_links_47 FOREIGN KEY (revoked_by) REFERENCES public.user_profiles (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.coaches ADD CONSTRAINT fk_coaches_48 FOREIGN KEY (academy_id) REFERENCES public.academies (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.coaches ADD CONSTRAINT fk_coaches_49 FOREIGN KEY (created_by) REFERENCES public.user_profiles (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.coaches ADD CONSTRAINT fk_coaches_50 FOREIGN KEY (updated_by) REFERENCES public.user_profiles (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.coaches ADD CONSTRAINT fk_coaches_51 FOREIGN KEY (deleted_by) REFERENCES public.user_profiles (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.coaches ADD CONSTRAINT fk_coaches_52 FOREIGN KEY (academy_id, membership_id) REFERENCES public.academy_memberships (academy_id, id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.stadiums ADD CONSTRAINT fk_stadiums_53 FOREIGN KEY (academy_id) REFERENCES public.academies (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.stadiums ADD CONSTRAINT fk_stadiums_54 FOREIGN KEY (created_by) REFERENCES public.user_profiles (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.stadiums ADD CONSTRAINT fk_stadiums_55 FOREIGN KEY (updated_by) REFERENCES public.user_profiles (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.stadiums ADD CONSTRAINT fk_stadiums_56 FOREIGN KEY (deleted_by) REFERENCES public.user_profiles (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.courts ADD CONSTRAINT fk_courts_57 FOREIGN KEY (academy_id) REFERENCES public.academies (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.courts ADD CONSTRAINT fk_courts_58 FOREIGN KEY (created_by) REFERENCES public.user_profiles (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.courts ADD CONSTRAINT fk_courts_59 FOREIGN KEY (updated_by) REFERENCES public.user_profiles (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.courts ADD CONSTRAINT fk_courts_60 FOREIGN KEY (deleted_by) REFERENCES public.user_profiles (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.courts ADD CONSTRAINT fk_courts_61 FOREIGN KEY (academy_id, stadium_id) REFERENCES public.stadiums (academy_id, id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.service_offers ADD CONSTRAINT fk_service_offers_62 FOREIGN KEY (academy_id) REFERENCES public.academies (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.service_offers ADD CONSTRAINT fk_service_offers_63 FOREIGN KEY (created_by) REFERENCES public.user_profiles (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.service_offers ADD CONSTRAINT fk_service_offers_64 FOREIGN KEY (updated_by) REFERENCES public.user_profiles (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.service_offers ADD CONSTRAINT fk_service_offers_65 FOREIGN KEY (academy_id, offer_key, supersedes_id) REFERENCES public.service_offers (academy_id, offer_key, id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.player_packages ADD CONSTRAINT fk_player_packages_66 FOREIGN KEY (academy_id) REFERENCES public.academies (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.player_packages ADD CONSTRAINT fk_player_packages_67 FOREIGN KEY (created_by) REFERENCES public.user_profiles (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.player_packages ADD CONSTRAINT fk_player_packages_68 FOREIGN KEY (updated_by) REFERENCES public.user_profiles (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.player_packages ADD CONSTRAINT fk_player_packages_69 FOREIGN KEY (academy_id, player_id) REFERENCES public.players (academy_id, id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.player_packages ADD CONSTRAINT fk_player_packages_70 FOREIGN KEY (academy_id, service_offer_id) REFERENCES public.service_offers (academy_id, id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE private.course_ledger ADD CONSTRAINT fk_course_ledger_71 FOREIGN KEY (academy_id) REFERENCES public.academies (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE private.course_ledger ADD CONSTRAINT fk_course_ledger_72 FOREIGN KEY (operation_id) REFERENCES private.command_receipts (id) ON UPDATE RESTRICT ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE private.course_ledger ADD CONSTRAINT fk_course_ledger_73 FOREIGN KEY (actor_user_id) REFERENCES public.user_profiles (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE private.course_ledger ADD CONSTRAINT fk_course_ledger_74 FOREIGN KEY (academy_id, package_id) REFERENCES public.player_packages (academy_id, id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE private.course_ledger ADD CONSTRAINT fk_course_ledger_75 FOREIGN KEY (academy_id, package_id, booking_id) REFERENCES public.bookings (academy_id, package_id, id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE private.course_ledger ADD CONSTRAINT fk_course_ledger_76 FOREIGN KEY (academy_id, package_id, reverses_entry_id) REFERENCES private.course_ledger (academy_id, package_id, id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.sessions ADD CONSTRAINT fk_sessions_77 FOREIGN KEY (academy_id) REFERENCES public.academies (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.sessions ADD CONSTRAINT fk_sessions_78 FOREIGN KEY (created_by) REFERENCES public.user_profiles (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.sessions ADD CONSTRAINT fk_sessions_79 FOREIGN KEY (updated_by) REFERENCES public.user_profiles (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.sessions ADD CONSTRAINT fk_sessions_80 FOREIGN KEY (academy_id, service_offer_id) REFERENCES public.service_offers (academy_id, id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.sessions ADD CONSTRAINT fk_sessions_81 FOREIGN KEY (academy_id, coach_id) REFERENCES public.coaches (academy_id, id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.sessions ADD CONSTRAINT fk_sessions_82 FOREIGN KEY (academy_id, stadium_id) REFERENCES public.stadiums (academy_id, id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.sessions ADD CONSTRAINT fk_sessions_83 FOREIGN KEY (academy_id, stadium_id, court_id) REFERENCES public.courts (academy_id, stadium_id, id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.bookings ADD CONSTRAINT fk_bookings_84 FOREIGN KEY (academy_id) REFERENCES public.academies (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.bookings ADD CONSTRAINT fk_bookings_85 FOREIGN KEY (deleted_by) REFERENCES public.user_profiles (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.bookings ADD CONSTRAINT fk_bookings_86 FOREIGN KEY (academy_id, session_id) REFERENCES public.sessions (academy_id, id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.bookings ADD CONSTRAINT fk_bookings_87 FOREIGN KEY (academy_id, player_id) REFERENCES public.players (academy_id, id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.bookings ADD CONSTRAINT fk_bookings_88 FOREIGN KEY (academy_id, service_offer_id) REFERENCES public.service_offers (academy_id, id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.bookings ADD CONSTRAINT fk_bookings_89 FOREIGN KEY (academy_id, community_course_id) REFERENCES public.community_courses (academy_id, id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.bookings ADD CONSTRAINT fk_bookings_90 FOREIGN KEY (created_by) REFERENCES public.user_profiles (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.bookings ADD CONSTRAINT fk_bookings_91 FOREIGN KEY (notification_owner_id) REFERENCES public.user_profiles (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.bookings ADD CONSTRAINT fk_bookings_92 FOREIGN KEY (academy_id, player_id, package_id) REFERENCES public.player_packages (academy_id, player_id, id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE private.booking_events ADD CONSTRAINT fk_booking_events_93 FOREIGN KEY (academy_id) REFERENCES public.academies (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE private.booking_events ADD CONSTRAINT fk_booking_events_94 FOREIGN KEY (operation_id) REFERENCES private.command_receipts (id) ON UPDATE RESTRICT ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE private.booking_events ADD CONSTRAINT fk_booking_events_95 FOREIGN KEY (actor_user_id) REFERENCES public.user_profiles (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE private.booking_events ADD CONSTRAINT fk_booking_events_96 FOREIGN KEY (academy_id, booking_id) REFERENCES public.bookings (academy_id, id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.booking_attendance ADD CONSTRAINT fk_booking_attendance_97 FOREIGN KEY (academy_id) REFERENCES public.academies (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.booking_attendance ADD CONSTRAINT fk_booking_attendance_98 FOREIGN KEY (academy_id, booking_id) REFERENCES public.bookings (academy_id, id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.booking_attendance ADD CONSTRAINT fk_booking_attendance_99 FOREIGN KEY (recorded_by) REFERENCES public.user_profiles (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.player_evaluations ADD CONSTRAINT fk_player_evaluations_100 FOREIGN KEY (academy_id) REFERENCES public.academies (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.player_evaluations ADD CONSTRAINT fk_player_evaluations_101 FOREIGN KEY (academy_id, session_id, booking_id) REFERENCES public.bookings (academy_id, session_id, id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.player_evaluations ADD CONSTRAINT fk_player_evaluations_102 FOREIGN KEY (academy_id, session_id, coach_id) REFERENCES public.sessions (academy_id, id, coach_id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.player_evaluations ADD CONSTRAINT fk_player_evaluations_103 FOREIGN KEY (recorded_by) REFERENCES public.user_profiles (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.academy_payments ADD CONSTRAINT fk_academy_payments_104 FOREIGN KEY (academy_id) REFERENCES public.academies (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.academy_payments ADD CONSTRAINT fk_academy_payments_105 FOREIGN KEY (academy_id, player_id) REFERENCES public.players (academy_id, id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.academy_payments ADD CONSTRAINT fk_academy_payments_106 FOREIGN KEY (academy_id, player_id, package_id) REFERENCES public.player_packages (academy_id, player_id, id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.academy_payments ADD CONSTRAINT fk_academy_payments_107 FOREIGN KEY (confirmed_by) REFERENCES public.user_profiles (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.academy_payments ADD CONSTRAINT fk_academy_payments_108 FOREIGN KEY (created_by) REFERENCES public.user_profiles (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.academy_payments ADD CONSTRAINT fk_academy_payments_109 FOREIGN KEY (operation_id) REFERENCES private.command_receipts (id) ON UPDATE RESTRICT ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.academy_invoices ADD CONSTRAINT fk_academy_invoices_110 FOREIGN KEY (academy_id) REFERENCES public.academies (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.academy_invoices ADD CONSTRAINT fk_academy_invoices_111 FOREIGN KEY (academy_id, player_id) REFERENCES public.players (academy_id, id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.academy_invoices ADD CONSTRAINT fk_academy_invoices_112 FOREIGN KEY (academy_id, payment_id) REFERENCES public.academy_payments (academy_id, id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.academy_invoices ADD CONSTRAINT fk_academy_invoices_113 FOREIGN KEY (academy_id, player_id, payment_id) REFERENCES public.academy_payments (academy_id, player_id, id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.academy_invoices ADD CONSTRAINT fk_academy_invoices_114 FOREIGN KEY (created_by) REFERENCES public.user_profiles (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.academy_invoices ADD CONSTRAINT fk_academy_invoices_115 FOREIGN KEY (operation_id) REFERENCES private.command_receipts (id) ON UPDATE RESTRICT ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.tournaments ADD CONSTRAINT fk_tournaments_116 FOREIGN KEY (academy_id) REFERENCES public.academies (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.tournaments ADD CONSTRAINT fk_tournaments_117 FOREIGN KEY (created_by) REFERENCES public.user_profiles (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.tournaments ADD CONSTRAINT fk_tournaments_118 FOREIGN KEY (updated_by) REFERENCES public.user_profiles (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.tournaments ADD CONSTRAINT fk_tournaments_119 FOREIGN KEY (deleted_by) REFERENCES public.user_profiles (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.tournaments ADD CONSTRAINT fk_tournaments_120 FOREIGN KEY (academy_id, cover_asset_id) REFERENCES private.academy_assets (academy_id, id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.academy_subscriptions ADD CONSTRAINT fk_academy_subscriptions_121 FOREIGN KEY (academy_id) REFERENCES public.academies (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE public.academy_subscriptions ADD CONSTRAINT fk_academy_subscriptions_122 FOREIGN KEY (plan_id) REFERENCES public.platform_plans (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE private.subscription_events ADD CONSTRAINT fk_subscription_events_123 FOREIGN KEY (academy_id) REFERENCES public.academies (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE private.subscription_events ADD CONSTRAINT fk_subscription_events_124 FOREIGN KEY (operation_id) REFERENCES private.command_receipts (id) ON UPDATE RESTRICT ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE private.subscription_events ADD CONSTRAINT fk_subscription_events_125 FOREIGN KEY (actor_user_id) REFERENCES public.user_profiles (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE private.subscription_events ADD CONSTRAINT fk_subscription_events_126 FOREIGN KEY (academy_id, subscription_id) REFERENCES public.academy_subscriptions (academy_id, id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE private.academy_notification_recipients ADD CONSTRAINT fk_academy_notification_recipients_127 FOREIGN KEY (academy_id) REFERENCES public.academies (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE private.academy_notification_recipients ADD CONSTRAINT fk_academy_notification_recipients_128 FOREIGN KEY (updated_by) REFERENCES public.user_profiles (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE private.notification_events ADD CONSTRAINT fk_notification_events_129 FOREIGN KEY (academy_id) REFERENCES public.academies (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE private.notification_events ADD CONSTRAINT fk_notification_events_130 FOREIGN KEY (operation_id) REFERENCES private.command_receipts (id) ON UPDATE RESTRICT ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE private.notification_events ADD CONSTRAINT fk_notification_events_131 FOREIGN KEY (academy_id, booking_id) REFERENCES public.bookings (academy_id, id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE private.notification_events ADD CONSTRAINT fk_notification_events_132 FOREIGN KEY (academy_id, invitation_id) REFERENCES private.academy_invitations (academy_id, id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE private.notification_events ADD CONSTRAINT fk_notification_events_133 FOREIGN KEY (subject_user_id) REFERENCES public.user_profiles (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE private.notification_deliveries ADD CONSTRAINT fk_notification_deliveries_134 FOREIGN KEY (academy_id) REFERENCES public.academies (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE private.notification_deliveries ADD CONSTRAINT fk_notification_deliveries_135 FOREIGN KEY (event_id) REFERENCES private.notification_events (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE private.notification_deliveries ADD CONSTRAINT fk_notification_deliveries_136 FOREIGN KEY (academy_id, event_id) REFERENCES private.notification_events (academy_id, id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE private.notification_payloads ADD CONSTRAINT fk_notification_payloads_137 FOREIGN KEY (academy_id) REFERENCES public.academies (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE private.notification_payloads ADD CONSTRAINT fk_notification_payloads_138 FOREIGN KEY (delivery_id) REFERENCES private.notification_deliveries (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE private.notification_payloads ADD CONSTRAINT fk_notification_payloads_139 FOREIGN KEY (academy_id, delivery_id) REFERENCES private.notification_deliveries (academy_id, id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE private.notification_webhook_receipts ADD CONSTRAINT fk_notification_webhook_receipts_140 FOREIGN KEY (academy_id) REFERENCES public.academies (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE private.notification_webhook_receipts ADD CONSTRAINT fk_notification_webhook_receipts_141 FOREIGN KEY (delivery_id) REFERENCES private.notification_deliveries (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE private.notification_webhook_receipts ADD CONSTRAINT fk_notification_webhook_receipts_142 FOREIGN KEY (academy_id, delivery_id) REFERENCES private.notification_deliveries (academy_id, id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE private.booking_reminders ADD CONSTRAINT fk_booking_reminders_143 FOREIGN KEY (academy_id) REFERENCES public.academies (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE private.booking_reminders ADD CONSTRAINT fk_booking_reminders_144 FOREIGN KEY (academy_id, booking_id) REFERENCES public.bookings (academy_id, id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE private.booking_reminders ADD CONSTRAINT fk_booking_reminders_145 FOREIGN KEY (academy_id, event_id) REFERENCES private.notification_events (academy_id, id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE private.audit_log ADD CONSTRAINT fk_audit_log_146 FOREIGN KEY (academy_id) REFERENCES public.academies (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE private.audit_log ADD CONSTRAINT fk_audit_log_147 FOREIGN KEY (operation_id) REFERENCES private.command_receipts (id) ON UPDATE RESTRICT ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE private.audit_log ADD CONSTRAINT fk_audit_log_148 FOREIGN KEY (actor_user_id) REFERENCES public.user_profiles (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE private.command_receipts ADD CONSTRAINT fk_command_receipts_149 FOREIGN KEY (academy_id) REFERENCES public.academies (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE private.command_receipts ADD CONSTRAINT fk_command_receipts_150 FOREIGN KEY (actor_user_id) REFERENCES public.user_profiles (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE private.academy_assets ADD CONSTRAINT fk_academy_assets_151 FOREIGN KEY (academy_id) REFERENCES public.academies (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE private.academy_assets ADD CONSTRAINT fk_academy_assets_152 FOREIGN KEY (academy_id, tournament_id) REFERENCES public.tournaments (academy_id, id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE private.academy_assets ADD CONSTRAINT fk_academy_assets_153 FOREIGN KEY (uploaded_by) REFERENCES public.user_profiles (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE private.academy_assets ADD CONSTRAINT fk_academy_assets_154 FOREIGN KEY (operation_id) REFERENCES private.command_receipts (id) ON UPDATE RESTRICT ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;

-- btree_gist operator classes are resolved from the extensions schema.
SET search_path = public, extensions, pg_catalog;
ALTER TABLE public.sessions ADD CONSTRAINT sessions_court_no_overlap
  EXCLUDE USING gist (academy_id WITH =, court_id WITH =, tstzrange(starts_at, ends_at, '[)') WITH &&)
  WHERE (court_id IS NOT NULL AND status IN ('OPEN','CLOSED'));
ALTER TABLE public.sessions ADD CONSTRAINT sessions_coach_no_overlap
  EXCLUDE USING gist (academy_id WITH =, coach_id WITH =, tstzrange(starts_at, ends_at, '[)') WITH &&)
  WHERE (status IN ('OPEN','CLOSED'));
RESET search_path;
