import { useEffect, useState } from 'react'
import { Alert, Box, Button, Card, CardContent, Chip, CircularProgress, Dialog, DialogActions, DialogContent, DialogTitle, FormControl, IconButton, InputLabel, MenuItem, Select, Stack, TextField, Tooltip, Typography } from '@mui/material'
import { AddRounded, DeleteOutlineRounded, EditRounded, GroupsRounded, VisibilityOffRounded, VisibilityRounded } from '@mui/icons-material'
import { collection, onSnapshot, query, where } from 'firebase/firestore'
import { db } from '../firebase'
import { createCommunity, createCommunityCourse, softDeleteCommunity, softDeleteCommunityCourse, updateCommunity, updateCommunityCourse } from '../services/managementService'
import { useI18n } from '../i18n'

interface Community { id: string; name: string; description: string; active: boolean }
interface Course { id: string; communityId: string; name: string; description: string }

export function CommunityManager({ academyId, notify }: { academyId: string; notify: (message: string) => void }) {
  const { t } = useI18n()
  const [communities, setCommunities] = useState<Community[]>([]); const [courses, setCourses] = useState<Course[]>([])
  const [community, setCommunity] = useState({ name: '', description: '' }); const [course, setCourse] = useState({ communityId: '', name: '', description: '' })
  const [editing, setEditing] = useState<Community | null>(null)
  const [editingCourse, setEditingCourse] = useState<Course | null>(null)
  const [deleteTarget, setDeleteTarget] = useState<{ type: 'community' | 'course'; id: string; name: string } | null>(null)
  const [saving, setSaving] = useState<'community' | 'course' | 'edit' | string>(''); const [error, setError] = useState('')
  useEffect(() => {
    const stops = [
      onSnapshot(query(collection(db, 'communities'), where('academyId', '==', academyId)), snap => setCommunities(snap.docs.filter(doc => doc.get('isDelete') !== true).map(doc => ({ id: doc.id, name: doc.get('name'), description: doc.get('description') || '', active: doc.get('active') === true })))),
      onSnapshot(query(collection(db, 'communityCourses'), where('academyId', '==', academyId)), snap => setCourses(snap.docs.filter(doc => doc.get('active') === true && doc.get('isDelete') !== true).map(doc => ({ id: doc.id, communityId: doc.get('communityId'), name: doc.get('name'), description: doc.get('description') || '' })))),
    ]
    return () => stops.forEach(stop => stop())
  }, [academyId])
  const saveCommunity = async () => { if (!community.name.trim()) return; setSaving('community'); setError(''); try { await createCommunity({ academyId, name: community.name, description: community.description }); setCommunity({ name: '', description: '' }); notify(t('Communauté créée')) } catch (reason) { setError(reason instanceof Error ? t(reason.message) : t('Une erreur est survenue')) } finally { setSaving('') } }
  const saveCourse = async () => { if (!course.communityId || !course.name.trim()) return; setSaving('course'); setError(''); try { await createCommunityCourse(course); setCourse({ communityId: '', name: '', description: '' }); notify(t('Cours créé')) } catch (reason) { setError(reason instanceof Error ? t(reason.message) : t('Une erreur est survenue')) } finally { setSaving('') } }
  const saveEdit = async () => { if (!editing?.name.trim()) return; setSaving('edit'); setError(''); try { await updateCommunity({ communityId: editing.id, name: editing.name, description: editing.description, active: editing.active }); setEditing(null); notify(t('Communauté modifiée')) } catch (reason) { setError(reason instanceof Error ? t(reason.message) : t('Une erreur est survenue')) } finally { setSaving('') } }
  const saveCourseEdit = async () => { if (!editingCourse?.name.trim()) return; setSaving('course-edit'); setError(''); try { await updateCommunityCourse({ courseId: editingCourse.id, name: editingCourse.name, description: editingCourse.description }); setEditingCourse(null); notify(t('Cours modifié')) } catch (reason) { setError(reason instanceof Error ? t(reason.message) : t('Une erreur est survenue')) } finally { setSaving('') } }
  const toggleVisibility = async (item: Community) => { setSaving(item.id); setError(''); try { await updateCommunity({ communityId: item.id, name: item.name, description: item.description, active: !item.active }); notify(t(item.active ? 'Communauté masquée' : 'Communauté affichée')) } catch (reason) { setError(reason instanceof Error ? t(reason.message) : t('Une erreur est survenue')) } finally { setSaving('') } }
  const confirmDelete = async () => { if (!deleteTarget) return; setSaving('delete'); setError(''); try { if (deleteTarget.type === 'community') await softDeleteCommunity(deleteTarget.id); else await softDeleteCommunityCourse(deleteTarget.id); notify(t(deleteTarget.type === 'community' ? 'Communauté supprimée' : 'Cours supprimé')); setDeleteTarget(null) } catch (reason) { setError(reason instanceof Error ? t(reason.message) : t('Une erreur est survenue')) } finally { setSaving('') } }
  return <Stack gap={2.5}>{error && <Alert severity="error">{error}</Alert>}
    <Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', md: '1fr 1fr' }, gap: 2 }}>
      <Card><CardContent><Stack gap={2}><Box><Typography variant="h6">{t('Créer une communauté')}</Typography><Typography color="text.secondary">{t('Regroupez les joueurs autour d’un catalogue de cours.')}</Typography></Box><TextField label={t('Nom de la communauté')} value={community.name} onChange={e => setCommunity({ ...community, name: e.target.value })} /><TextField multiline minRows={3} label={t('Description facultative')} value={community.description} onChange={e => setCommunity({ ...community, description: e.target.value })} /><Button variant="contained" startIcon={saving === 'community' ? <CircularProgress size={18} color="inherit" /> : <GroupsRounded />} disabled={saving !== '' || !community.name.trim()} onClick={saveCommunity}>{t('Créer la communauté')}</Button></Stack></CardContent></Card>
      <Card><CardContent><Stack gap={2}><Box><Typography variant="h6">{t('Créer un cours communautaire')}</Typography><Typography color="text.secondary">{t('La configuration de séance sera choisie au moment de la réservation.')}</Typography></Box><FormControl><InputLabel>{t('Communauté')}</InputLabel><Select label={t('Communauté')} value={course.communityId} onChange={e => setCourse({ ...course, communityId: e.target.value })}>{communities.filter(item => item.active).map(item => <MenuItem key={item.id} value={item.id}>{item.name}</MenuItem>)}</Select></FormControl><TextField label={t('Nom du cours')} value={course.name} onChange={e => setCourse({ ...course, name: e.target.value })} /><TextField multiline minRows={2} label={t('Description facultative')} value={course.description} onChange={e => setCourse({ ...course, description: e.target.value })} /><Button variant="contained" startIcon={saving === 'course' ? <CircularProgress size={18} color="inherit" /> : <AddRounded />} disabled={saving !== '' || !course.communityId || !course.name.trim()} onClick={saveCourse}>{t('Créer le cours')}</Button></Stack></CardContent></Card>
    </Box>
    <Card><CardContent><Typography variant="h6" mb={2}>{t('Communautés et cours')}</Typography>{!communities.length ? <Alert severity="info">{t('Aucune communauté créée.')}</Alert> : <Stack gap={1.5}>{communities.map(item => <Box key={item.id} sx={{ p: 2, border: '1px solid', borderColor: 'divider', borderRadius: 3, opacity: item.active ? 1 : .65 }}><Stack direction="row" alignItems="center" gap={1}><Box flex={1}><Stack direction="row" alignItems="center" gap={1}><Typography fontWeight={800}>{item.name}</Typography><Chip size="small" label={t(item.active ? 'Visible' : 'Masquée')} color={item.active ? 'success' : 'default'} /></Stack>{item.description && <Typography variant="body2" color="text.secondary">{item.description}</Typography>}</Box><Tooltip title={t('Modifier')}><IconButton onClick={() => setEditing({ ...item })} disabled={saving !== ''}><EditRounded /></IconButton></Tooltip><Tooltip title={t(item.active ? 'Masquer' : 'Afficher')}><IconButton onClick={() => void toggleVisibility(item)} disabled={saving !== ''}>{saving === item.id ? <CircularProgress size={20} /> : item.active ? <VisibilityOffRounded /> : <VisibilityRounded />}</IconButton></Tooltip><Tooltip title={t('Supprimer la communauté')}><IconButton color="error" onClick={() => setDeleteTarget({ type: 'community', id: item.id, name: item.name })} disabled={saving !== ''}><DeleteOutlineRounded /></IconButton></Tooltip></Stack><Stack gap={.75} mt={1}>{courses.filter(value => value.communityId === item.id).map(value => <Stack key={value.id} direction="row" alignItems="center" sx={{ bgcolor: 'action.hover', px: 1.2, py: .5, borderRadius: 2 }}><Box flex={1}><Typography variant="body2" fontWeight={700}>{value.name}</Typography>{value.description && <Typography variant="caption" color="text.secondary">{value.description}</Typography>}</Box><Tooltip title={t('Modifier le cours')}><IconButton size="small" onClick={() => setEditingCourse({ ...value })} disabled={saving !== ''}><EditRounded fontSize="small" /></IconButton></Tooltip><Tooltip title={t('Supprimer le cours')}><IconButton size="small" color="error" onClick={() => setDeleteTarget({ type: 'course', id: value.id, name: value.name })} disabled={saving !== ''}><DeleteOutlineRounded fontSize="small" /></IconButton></Tooltip></Stack>)}{!courses.some(value => value.communityId === item.id) && <Typography variant="caption" color="text.secondary">{t('Aucun cours.')}</Typography>}</Stack></Box>)}</Stack>}</CardContent></Card>
    <Dialog open={Boolean(editing)} onClose={() => saving !== 'edit' && setEditing(null)} fullWidth maxWidth="sm"><DialogTitle>{t('Modifier la communauté')}</DialogTitle><DialogContent><Stack gap={2} pt={1}><TextField label={t('Nom de la communauté')} value={editing?.name ?? ''} onChange={e => editing && setEditing({ ...editing, name: e.target.value })} /><TextField multiline minRows={3} label={t('Description facultative')} value={editing?.description ?? ''} onChange={e => editing && setEditing({ ...editing, description: e.target.value })} /></Stack></DialogContent><DialogActions><Button onClick={() => setEditing(null)} disabled={saving === 'edit'}>{t('Annuler')}</Button><Button variant="contained" onClick={() => void saveEdit()} disabled={saving === 'edit' || !editing?.name.trim()}>{saving === 'edit' ? <CircularProgress size={20} color="inherit" /> : t('Enregistrer')}</Button></DialogActions></Dialog>
    <Dialog open={Boolean(editingCourse)} onClose={() => saving !== 'course-edit' && setEditingCourse(null)} fullWidth maxWidth="sm"><DialogTitle>{t('Modifier le cours communautaire')}</DialogTitle><DialogContent><Stack gap={2} pt={1}><TextField label={t('Nom du cours')} value={editingCourse?.name ?? ''} onChange={e => editingCourse && setEditingCourse({ ...editingCourse, name: e.target.value })} /><TextField multiline minRows={3} label={t('Description facultative')} value={editingCourse?.description ?? ''} onChange={e => editingCourse && setEditingCourse({ ...editingCourse, description: e.target.value })} /></Stack></DialogContent><DialogActions><Button onClick={() => setEditingCourse(null)} disabled={saving === 'course-edit'}>{t('Annuler')}</Button><Button variant="contained" onClick={() => void saveCourseEdit()} disabled={saving === 'course-edit' || !editingCourse?.name.trim()}>{saving === 'course-edit' ? <CircularProgress size={20} color="inherit" /> : t('Enregistrer')}</Button></DialogActions></Dialog>
    <Dialog open={Boolean(deleteTarget)} onClose={() => saving !== 'delete' && setDeleteTarget(null)} fullWidth maxWidth="xs"><DialogTitle>{t(deleteTarget?.type === 'community' ? 'Supprimer la communauté ?' : 'Supprimer le cours ?')}</DialogTitle><DialogContent><Typography>{t(deleteTarget?.type === 'community' ? 'La communauté et tous ses cours seront masqués sans suppression définitive des données.' : 'Ce cours sera masqué sans suppression définitive de ses données.')}</Typography><Typography fontWeight={800} mt={1}>{deleteTarget?.name}</Typography></DialogContent><DialogActions><Button onClick={() => setDeleteTarget(null)} disabled={saving === 'delete'}>{t('Annuler')}</Button><Button variant="contained" color="error" onClick={() => void confirmDelete()} disabled={saving === 'delete'} startIcon={saving === 'delete' ? <CircularProgress size={16} color="inherit" /> : <DeleteOutlineRounded />}>{t('Supprimer')}</Button></DialogActions></Dialog>
  </Stack>
}
