/* eslint-disable react-refresh/only-export-components */
import { createContext, useCallback, useContext, useEffect, useMemo, useState, type ReactNode } from 'react'

export type Language = 'fr' | 'en'
const english: Record<string, string> = {
  "Paiement": "Payment",
  "Padel": "Padel",
  "Imprimer": "Print",
  "Télécharger le PDF": "Download PDF",
  "Partager la facture": "Share invoice",
  "Ouverture du partage…": "Opening sharing…",
  "La facture est imprimée, téléchargée et partagée dans la langue actuelle de l’administration.": "The invoice is printed, downloaded and shared in the current administration language.",
  "Le partage direct n’est pas disponible. Le PDF a été téléchargé : joignez-le à votre message au client.": "Direct sharing is unavailable. The PDF has been downloaded: attach it to your message to the customer.",
  "Le partage a échoué. Téléchargez le PDF pour le joindre à votre message.": "Sharing failed. Download the PDF and attach it to your message.",
  "Impossible de créer le PDF. Vous pouvez utiliser l’impression.": "Unable to create the PDF. You can use printing instead.",

  "Facture": "Invoice",
  "Facture acquittée": "Paid invoice",
  "Date du paiement": "Payment date",
  "Paiement confirmé — espèces": "Payment confirmed — cash",
  "Émetteur": "Issuer",
  "Académie non renseignée": "Academy not specified",
  "Client": "Customer",
  "Description": "Description",
  "Montant payé": "Amount paid",
  "Total payé": "Total paid",
  "Solde à payer": "Balance due",
  "cours": "lessons",
  "Document établi à partir du paiement confirmé. Aucun détail de taxe n’est enregistré pour ce paiement.": "Document based on the confirmed payment. No tax breakdown is recorded for this payment.",
  "Pour télécharger le PDF, choisissez « Enregistrer au format PDF » dans la fenêtre d’impression.": "To download the PDF, choose “Save as PDF” in the print dialog.",
  "Imprimer / Enregistrer en PDF": "Print / Save as PDF",
  "Ce paiement ancien ne possède pas de facture enregistrée.": "This older payment has no saved invoice.",

  "Suivi des emails": "Email delivery tracking",
  "Consultez les livraisons et relancez les échecs récupérables.": "Check delivery status and retry recoverable failures.",
  "En attente d’envoi": "Queued for sending",
  "Ancien envoi en attente": "Legacy pending email",
  "Envoi en cours": "Sending",
  "Nouvelle tentative programmée": "Retry scheduled",
  "Accepté par le service email": "Accepted by email service",
  "Envoyé (ancien suivi)": "Sent (legacy tracking)",
  "Livré": "Delivered",
  "Livraison différée": "Delivery deferred",
  "Échec": "Failed",
  "Résultat à vérifier": "Needs verification",
  "Adresse rejetée": "Address rejected",
  "Email bloqué": "Email blocked",
  "Signalé comme indésirable": "Reported as spam",
  "Toutes les académies": "All academies",
  "Afficher les notifications": "Show notifications",
  "Certains envois ont un résultat incertain. Vérifiez leur historique dans Brevo avant tout nouvel envoi.": "Some email results are uncertain. Check their history in Brevo before sending again.",
  "Aucune notification": "No notifications",
  "Adresse manquante": "Missing address",
  "Relancer l’envoi": "Retry delivery",
  "Motif": "Reason",
  "Référence email": "Email reference",
  "Afficher la suite": "Load more",
  "Coach créé, invitation en attente d’envoi": "Coach created, invitation queued",
  "Invitation en attente d’envoi": "Invitation queued",
  "Administrateur créé, invitation en attente d’envoi": "Administrator created, invitation queued",
  "Compte coach créé. Le lien reste disponible pour un partage manuel si nécessaire.": "Coach account created. You can still share this link manually if needed.",
  "Un nouveau lien a été généré. Il reste disponible pour un partage manuel si nécessaire.": "A new link has been generated. You can still share it manually if needed.",
  'Rappel devenu inutile': 'Reminder no longer needed',
  'Créneaux Paddle':'Padel slots','Configurez la durée et le montant de chaque créneau.':'Set the duration and price of each slot.','Configurez les durées et montants proposés pour le Paddle.':'Set the durations and prices offered for Padel.','Vérifiez la durée et le montant.':'Check the duration and price.','Un créneau Paddle existe déjà pour cette durée.':'A Padel slot already exists for this duration.','Créneau':'Slot','Le nom et le prénom du joueur sont requis.':'The player’s first and last names are required.',
  'Rechercher un utilisateur':'Search for a user','Nom ou adresse e-mail':'Name or email address','Ce joueur est déjà attribué à un utilisateur. Un joueur ne peut être lié qu’à un seul utilisateur.':'This player is already assigned to a user. A player can only be linked to one user.','Ce joueur est déjà attribué à un autre utilisateur.':'This player is already assigned to another user.','Ce joueur possède déjà une attribution. Corrigez ses liaisons existantes avant de continuer.':'This player already has an assignment. Fix its existing links before continuing.',
  'Configuration des créneaux Paddle':'Padel slot settings','Configurez les horaires, durées et montants proposés pour le Paddle.':'Configure the schedules, durations and prices offered for Padel.','Configuration des créneaux':'Slot settings',
  'Sport':'Sport','Choix du sport':'Sport selection','Tennis':'Tennis','Paddle':'Padel',
  'Créneaux Paddle hebdomadaires':'Weekly Padel slots','Configurez le jour, l’heure de début, la durée et le montant de chaque créneau.':'Set the day, start time, duration and price for each slot.','Ajouter un créneau':'Add a slot','Aucun créneau Paddle configuré.':'No Padel slot configured.','Nouveau créneau Paddle':'New Padel slot','Modifier le créneau Paddle':'Edit Padel slot','Créneau Paddle ajouté':'Padel slot added','Créneau Paddle modifié':'Padel slot updated','Créneau Paddle supprimé':'Padel slot deleted','Supprimer ce créneau Paddle ?':'Delete this Padel slot?','Impossible de charger les créneaux Paddle.':'Unable to load Padel slots.','Vérifiez le jour, l’heure, la durée et le montant.':'Check the day, time, duration and amount.','Jour':'Day','Durée':'Duration','minutes':'minutes','Lundi':'Monday','Mardi':'Tuesday','Mercredi':'Wednesday','Jeudi':'Thursday','Vendredi':'Friday','Samedi':'Saturday','Dimanche':'Sunday','Jour invalide.':'Invalid day.','Heure de début invalide.':'Invalid start time.','La durée doit être comprise entre 15 et 480 minutes.':'Duration must be between 15 and 480 minutes.','Créneau Paddle introuvable.':'Padel slot not found.','Un créneau Paddle existe déjà à ce jour et cette heure.':'A Padel slot already exists on this day at this time.',
  'Ce joueur possède déjà une réservation pendant cette tranche horaire.':'This player already has a booking during this time slot.','La tranche horaire de cette séance est invalide.':'This session time slot is invalid.',
  'Retirer le client du Booking':'Remove client from Booking','Supprimer la réservation':'Delete booking','Supprimer la réservation ?':'Delete booking?','La réservation sera masquée. Si elle était confirmée, la place et le cours seront restitués.':'The booking will be hidden. If it was confirmed, the place and lesson will be restored.','Retirer le client du Booking ?':'Remove client from Booking?','Toutes les réservations de ce client seront masquées dans le Booking. Son profil joueur restera disponible dans Joueurs & familles.':'All this client’s bookings will be hidden from Booking. Their player profile will remain available in Players & families.','Retirer':'Remove',
  'Navigation des réservations':'Booking navigation','Suivi des réservations':'Booking operations','Historique complet':'Full history','Date de début':'Start date','Date de fin':'End date','Filtrer':'Filter','Charger plus':'Load more','réservation chargée':'booking loaded','réservations chargées':'bookings loaded','Aucune réservation pour cette période.':'No bookings for this period.','Impossible de charger l’historique des réservations.':'Unable to load booking history.','La date de fin doit être postérieure ou égale à la date de début.':'The end date must be on or after the start date.','Lieu':'Location',
  'Cours du joueur':'Player lessons',
  'Vue d’ensemble':'Overview','Réservations':'Bookings','Joueurs & familles':'Players & families','Coachs':'Coaches','Tournois':'Tournaments','Communication':'Communication',
  'Paramètres':'Settings','Centre d’aide':'Help centre','GESTION':'MANAGEMENT','ACADÉMIE ACTIVE':'ACTIVE ACADEMY','joueurs':'players','terrains':'courts',
  'Déconnexion':'Sign out','PILOTEZ VOTRE ACADÉMIE':'RUN YOUR ACADEMY','Chaque cours. Chaque joueur. Au même endroit.':'Every lesson. Every player. All in one place.',
  'Réservations, terrains, coachs et familles : gardez une vision claire de votre club au quotidien.':'Bookings, courts, coaches and families: keep a clear daily view of your club.',
  'Bon retour 👋':'Welcome back 👋','Connectez-vous à l’espace d’administration SportA.':'Sign in to the SportA administration area.',
  'Adresse e-mail':'Email address','Mot de passe':'Password','Afficher le mot de passe':'Show password','Masquer le mot de passe':'Hide password',
  'Se souvenir de moi':'Remember me','Mot de passe oublié ?':'Forgot password?','Se connecter':'Sign in','COMPTE ROOT DE DÉMONSTRATION':'DEMO ROOT ACCOUNT',
  'Adresse e-mail ou mot de passe incorrect.':'Incorrect email address or password.','ADMINISTRATION':'ADMINISTRATION',
  'Ce compte ne possède pas les droits administrateur.':'This account does not have administrator privileges.','Connexion...':'Signing in...','Utilisez votre compte administrateur.':'Use your administrator account.',
  'Administration':'Administration','Gérez les accès et les ressources du réseau.':'Manage network access and resources.','Centre d’administration':'Administration centre','Gérez les accès et les ressources de vos académies.':'Manage access and resources across your academies.','Créer':'Create','Administrateurs':'Administrators','Académies':'Academies','Stades':'Stadiums','Suspendu':'Suspended','Modifier les accès':'Edit access','Administrateur créé':'Administrator created','Accès administrateur mis à jour':'Administrator access updated','Élément créé avec succès':'Item created successfully','Une erreur est survenue':'An error occurred','Compte créé':'Account created','Lien de définition du mot de passe':'Password setup link','Nom complet':'Full name','Rôle':'Role','IDs académies, séparés par des virgules':'Academy IDs, comma-separated','Nom':'Name','Ville':'City','Pays':'Country','Nom du stade':'Stadium name','Adresse':'Address','Nombre de terrains':'Number of courts','Spécialités, séparées par des virgules':'Specialties, comma-separated','Utilisez le bouton Créer pour ajouter un nouvel élément. Les listes seront connectées à la prochaine vue opérationnelle.':'Use the Create button to add a new item. Lists will be connected in the next operational view.',
  'Créez les comptes administrateurs et contrôlez leurs accès.':'Create administrator accounts and control their access.','Nouvel administrateur':'New administrator','Fermer':'Close','Nouvelle académie':'New academy','Académie créée':'Academy created','Gérez les clubs et centres de formation du réseau.':'Manage the network’s clubs and training centres.','Stades & terrains':'Stadiums & courts','Gérez les infrastructures sportives du réseau.':'Manage the network’s sports facilities.','Gérez les sites sportifs et leurs terrains.':'Manage sports venues and their courts.','Nouveau stade':'New stadium','Stade créé':'Stadium created','Créez les coachs et rattachez-les à leur académie.':'Create coaches and assign them to their academy.','Nouveau coach':'New coach','Coach créé':'Coach created','Coach créé et invitation envoyée':'Coach created and invitation sent','Coach créé, mais l’envoi de l’invitation a échoué':'Coach created, but the invitation could not be sent','Actions du coach':'Coach actions','Renvoyer le lien de mot de passe':'Resend password link','Supprimer le coach':'Delete coach','Nouveau lien généré':'New link generated','Nouveau lien généré et envoyé':'New link generated and sent','Nouveau lien généré, mais l’envoi a échoué':'New link generated, but delivery failed','Coach supprimé':'Coach deleted','Copier le lien':'Copy link','Lien de mot de passe':'Password link','Un nouveau lien a été généré. Envoyez-le au coach ; il remplace le lien expiré.':'A new link has been generated. Send it to the coach; it replaces the expired link.','Nouveau lien de mot de passe':'New password link','Réessayer':'Try again','Supprimer le coach ?':'Delete coach?','Le compte de':'The account of','sera définitivement supprimé. Cette action est irréversible.':'will be permanently deleted. This action cannot be undone.','La suppression sera refusée si ce coach possède encore une séance future.':'Deletion will be refused if this coach still has a future session.',
  'Académies (facultatif)':'Academies (optional)','Vous pourrez rattacher cet administrateur à une académie plus tard.':'You can assign this administrator to an academy later.','Le service de gestion des administrateurs n’est pas disponible. Déployez les Cloud Functions.':'The administrator management service is unavailable. Deploy the Cloud Functions.',
  'Bonjour':'Hello','Mon profil':'My profile','Gérez vos informations personnelles et vos préférences.':'Manage your personal information and preferences.','Informations personnelles':'Personal information','Nom d’utilisateur':'Username','Téléphone':'Phone','Langue préférée':'Preferred language','Enregistrer les modifications':'Save changes','Profil mis à jour':'Profile updated','L’adresse e-mail est gérée par Firebase Authentication.':'The email address is managed by Firebase Authentication.',
  'Refusée':'Rejected','Actions':'Actions','Approuver':'Approve','Refuser':'Reject','Terminer':'Complete','Réservation approuvée':'Booking approved','Réservation refusée':'Booking rejected','Réservation terminée':'Booking completed','Aucune réservation Firebase pour le moment.':'No Firebase bookings yet.','Aucune réservation pour ce filtre.':'No bookings match this filter.','ID joueur':'Player ID','réservation':'booking','réservations':'bookings','en attente':'pending','confirmée(s)':'confirmed','terminée(s)':'completed','Réservation récente':'Latest booking','Terrain':'Court','Créez d’abord un joueur et une séance disponible dans Firestore.':'First create a player and an available session in Firestore.','Note facultative':'Optional note','La réservation sera placée en attente jusqu’à son approbation.':'The booking will remain pending until it is approved.','Créer la réservation':'Create booking','Choix du créneau':'Slot choice','Utiliser un créneau existant':'Use an existing slot','Créer le créneau maintenant':'Create the slot now','Nouveau créneau':'New slot','Vous pouvez en créer un directement ici.':'You can create one directly here.',
  'Rechercher un joueur, une réservation...':'Search a player or booking...','Notifications':'Notifications','Notifications récentes':'Recent notifications','Administratrice':'Administrator',
  '3 réservations attendent validation':'3 bookings need approval','Lucas a gagné un nouveau badge':'Lucas earned a new badge','Tournoi complet à 80%':'Tournament 80% full','Message de Mme Ngono':'Message from Mrs Ngono',
  'Bonjour Sophie 👋':'Hello Sophie 👋','Voici ce qui se passe dans votre académie aujourd’hui.':'Here is what is happening at your academy today.',
  'Réservations & séances':'Bookings & sessions','Planifiez et suivez les opérations du club.':'Plan and monitor club operations.',
  'Suivez chaque enfant depuis son inscription.':'Follow every child from enrolment onward.','Équipe des coachs':'Coaching team','Pilotez les disponibilités et affectations.':'Manage availability and assignments.',
  'Gérez les inscriptions et les préparatifs.':'Manage registrations and event preparation.','Gardez les familles informées et engagées.':'Keep families informed and engaged.',
  'DIMANCHE 9 AOÛT':'SUNDAY, AUGUST 9','Nouvelle réservation':'New booking',
  'Joueurs actifs':'Active players','ce mois':'this month','Séances cette semaine':'Sessions this week','réalisées':'completed','Revenus du mois':'Monthly revenue','Tournois à venir':'Upcoming tournaments','inscrits':'registered',
  'terminées':'completed','Revenus validés':'Validated revenue','Confirmées et terminées':'Confirmed and completed','Données réelles':'Live data','Aucune réservation en attente.':'No pending bookings.',
  'Famille':'Family','Famille liée':'Linked family','Voir la famille':'View family','Âge non renseigné':'Age not provided','Aucun joueur enregistré pour le moment.':'No players registered yet.','Impossible de charger les joueurs.':'Unable to load players.','Aucun membre de la famille lié à ce joueur.':'No family member is linked to this player.','Non défini':'Not specified','Proche':'Relative','Père':'Father','Mère':'Mother','Frère':'Brother','Sœur':'Sister','Tuteur':'Guardian','En attente de confirmation':'Awaiting confirmation','Confirmer le paiement':'Confirm payment',
  'Revenus de la semaine':'Weekly revenue','Voir le rapport':'View report','Présence des joueurs':'Player attendance','Détails':'Details','Séances d’aujourd’hui':'Today’s sessions','Réservations récentes':'Recent bookings','Tout voir':'View all','À traiter':'Needs attention',
  'réservations en attente':'pending bookings','Validation requise':'Approval required','messages non lus':'unread messages','Parents et coachs':'Parents and coaches','places restantes':'spots left','nouvelles inscriptions':'new registrations','Dossiers à vérifier':'Files to review',
  'Toutes':'All','Confirmée':'Confirmed','En attente':'Pending','Terminée':'Completed','Annulée':'Cancelled','Référence':'Reference','Joueur':'Player','Date & heure':'Date & time','Séance':'Session','Coach':'Coach','Montant':'Amount','Statut':'Status',
  'Niveau':'Level','Académie':'Academy','Coach principal':'Main coach','Progression':'Progress','Séances':'Sessions','Parent lié':'Parent linked','Actif':'Active','En pause':'Paused',
  'Disponible':'Available','En séance':'In session','Absent':'Away','Voir le planning':'View schedule','Note':'Rating',
  'Inscriptions ouvertes':'Registration open','Complet':'Full','Exporter':'Export','Gérer':'Manage','Liste':'List','exportée':'exported','ouvert':'opened',
  'Rechercher...':'Search...','En ligne':'Online','Écrire un message...':'Write a message...','Envoyer':'Send','Message envoyé':'Message sent',
  'Annuler':'Cancel','Confirmer':'Confirm','Type de séance':'Session type','Date':'Date','Heure':'Time','Montant (F CFA)':'Amount (CFA francs)','Réservation créée avec succès':'Booking created successfully','Réservation mise à jour':'Booking updated',
  'Configuration des séances':'Session settings','Configurations enregistrées':'Saved configurations','Chaque tranche constitue une configuration réservable distincte.':'Each age range is a distinct bookable configuration.','Aucune configuration enregistrée.':'No saved configuration.','Tranche d’âge':'Age range','Configuration de séance':'Session configuration','Séance planifiée':'Scheduled session','Une tranche identique est mise à jour. Une nouvelle tranche crée une configuration distincte.':'An identical age range is updated. A new range creates a separate configuration.','Créez d’abord un joueur.':'First create a player.','Renseignez l’âge du joueur avant de réserver.':'Enter the player age before booking.','Aucune configuration ne correspond à l’âge de ce joueur.':'No configuration matches this player age.','Aucune configuration active ne correspond à l’âge de ce joueur.':'No active configuration matches this player age.','Aucune configuration ne correspond à l’âge de ce joueur dans son académie.':'No configuration matches this player age in their academy.','Aucun créneau planifié ne correspond à cette configuration.':'No scheduled slot matches this configuration.','Devise':'Currency','Dirham des Émirats arabes unis':'UAE dirham','Franc CFA':'CFA franc','Euro':'Euro','Dollar américain':'US dollar','Dirham marocain':'Moroccan dirham','Définissez les tarifs et les tranches d’âge autorisées.':'Define prices and permitted age ranges.','Catalogue des séances':'Session catalogue','Configurez le prix et l’éligibilité par âge. Ces valeurs seront appliquées aux nouvelles réservations.':'Configure pricing and age eligibility. These values will be applied to new bookings.','Séance privée':'Private session','Un joueur avec un coach.':'One player with one coach.','Séance semi-privée':'Semi-private session','Un petit groupe avec un accompagnement rapproché.':'A small group with close coaching.','Séance de groupe':'Group session','Un cours collectif pour plusieurs joueurs.':'A group lesson for several players.','Prix':'Price','Âge minimum':'Minimum age','Âge maximum':'Maximum age','Enregistrer':'Save','Configuration enregistrée':'Configuration saved','Configurée':'Configured','À configurer':'Needs configuration','Version':'Version','Vérifiez le prix et la tranche d’âge.':'Check the price and age range.','Créez ou rattachez d’abord une académie à votre compte.':'First create or assign an academy to your account.','Les changements s’appliquent uniquement aux futures réservations. Les réservations existantes conservent leur tarif.':'Changes apply only to future bookings. Existing bookings keep their original price.',
  'Veuillez renseigner tous les champs correctement.':'Please complete all fields correctly.','Date ou heure invalide.':'Invalid date or time.','La durée du créneau ne peut pas dépasser 8 heures.':'The slot duration cannot exceed 8 hours.','La date et les heures du créneau sont invalides.':'The slot date and times are invalid.','Court':'Court',
  'Session':'Session','Tennis session':'Tennis session','Paddle session':'Padel session','Configurez le prix et l’âge minimum. Ces valeurs seront appliquées aux nouvelles réservations.':'Configure the price and minimum age. These values will apply to new bookings.','Vérifiez le prix et l’âge minimum.':'Check the price and minimum age.','Une configuration existante avec le même âge minimum sera mise à jour.':'An existing configuration with the same minimum age will be updated.','Chaque âge minimum constitue une configuration réservable distincte.':'Each minimum age is a distinct bookable configuration.','À partir de':'From',
  'Âge maximum (facultatif)':'Maximum age (optional)','Vérifiez le prix et les âges renseignés.':'Check the price and entered ages.','L’âge maximum est facultatif.':'The maximum age is optional.',
  'ans':'years old','Rouge':'Red','Orange':'Orange','Vert':'Green','Initiation':'Beginner','Perfectionnement':'Advanced training','Jeu & Match':'Play & Match','Préparation tournoi':'Tournament preparation','Petit groupe':'Small group','Service & retour':'Serve & return',
  'Lun':'Mon','Mar':'Tue','Mer':'Wed','Jeu':'Thu','Ven':'Fri','Sam':'Sat','Dim':'Sun','Mars':'Mar','Avr.':'Apr','Mai':'May','Juin':'Jun','Juil.':'Jul','Août':'Aug',
  'Bonjour Sophie, Lucas a été très concentré aujourd’hui.':'Hi Sophie, Lucas was very focused today.','Son coup droit progresse vraiment bien 🎾':'His forehand is improving really well 🎾','Merci David ! Il était très fier de sa séance.':'Thank you David! He was very proud of his session.',
  'Créneaux planifiés':'Scheduled slots','Planifiez les dates, coachs, terrains et capacités proposés à la réservation.':'Schedule the dates, coaches, courts and capacities offered for booking.','Planifier un créneau':'Schedule a slot','Aucun créneau planifié.':'No scheduled slots.','Créneau planifié':'Slot scheduled','Numéro du terrain':'Court number','Capacité':'Capacity','Heure de début':'Start time','Heure de fin':'End time','Planifier':'Schedule','places':'spots',
  'Compte coach créé. Envoyez ce lien au coach pour définir son mot de passe.':'Coach account created. Send this link to the coach to set their password.','Lien de création du mot de passe':'Password setup link',
  'Stade (facultatif)':'Stadium (optional)','Numéro du terrain (facultatif)':'Court number (optional)','À définir plus tard':'Set later','À définir':'To be defined',
  'Communautés':'Communities','Créer une communauté':'Create a community','Regroupez les joueurs autour d’un catalogue de cours.':'Group players around a course catalogue.','Nom de la communauté':'Community name','Description facultative':'Optional description','Créer la communauté':'Create community','Créer un cours communautaire':'Create a community course','La configuration de séance sera choisie au moment de la réservation.':'The session configuration will be selected when booking.','Communauté':'Community','Nom du cours':'Course name','Créer le cours':'Create course','Communautés et cours':'Communities and courses','Aucune communauté créée.':'No community created.','Aucun cours.':'No courses.','Communauté créée':'Community created','Communauté modifiée':'Community updated','Communauté masquée':'Community hidden','Communauté affichée':'Community visible','Modifier la communauté':'Edit community','Visible':'Visible','Masquée':'Hidden','Masquer':'Hide','Afficher':'Show','Cours créé':'Course created','Communauté du joueur':'Player community','Aucune communauté':'No community','Attribuer':'Assign','Un joueur ne peut appartenir qu’à une seule communauté.':'A player can belong to only one community.','Non attribuée':'Not assigned','Rechercher et sélectionner un joueur':'Search and select a player','Cours de la communauté':'Community course','Ce joueur n’est rattaché à aucune communauté. Attribuez-lui une communauté dans le module Joueurs & famille.':'This player is not assigned to a community. Assign one in the Players & family module.','Aucun cours compatible n’est disponible dans la communauté de ce joueur.':'No compatible course is available in this player’s community.',
  'Profils joueurs':'Player profiles','Créez les joueurs et rattachez-les à leur famille.':'Create players and assign them to their family.','Créer un joueur':'Create player','Créer un profil joueur':'Create a player profile','Prénom':'First name','Âge':'Age','Sexe':'Gender','Fille':'Girl','Garçon':'Boy','Femme':'Female','Homme':'Man','Autre':'Other','Mode de paiement':'Payment method','Cash':'Cash','Carte bancaire':'Bank card','Lien de paiement':'Payment link','Virement bancaire':'Bank transfer','Attribuer à un utilisateur (facultatif)':'Assign to a user (optional)','Vous pourrez également attribuer le joueur plus tard.':'You can also assign the player later.','Le profil restera en attente jusqu’à la confirmation du paiement cash.':'The profile will remain pending until the cash payment is confirmed.','Créer le joueur':'Create player','Renseignez les informations du joueur et une séance compatible avec son âge.':'Enter the player details and choose a session compatible with their age.','Utilisateurs et joueurs rattachés':'Users and assigned players','Consultez chaque parent ou élève et les profils joueurs associés.':'View every parent or student and their associated player profiles.','Aucun utilisateur parent ou élève enregistré.':'No parent or student user is registered.','Utilisateur':'User','Contact':'Contact','Joueurs rattachés':'Assigned players','Aucun joueur':'No player','Attribuer à un utilisateur':'Assign to a user','Le joueur apparaîtra immédiatement dans le profil de cet utilisateur.':'The player will immediately appear in this user’s profile.','Impossible de charger les utilisateurs.':'Unable to load users.','parent':'Parent','student':'Student','séances':'sessions',
  'Modifier':'Edit','Supprimer':'Delete','Nombre de séances':'Number of sessions','Vérifiez le prix, le nombre de séances et les âges renseignés.':'Check the price, number of sessions and age values.','Supprimer cette configuration de séance ?':'Delete this session configuration?','Configuration supprimée':'Configuration deleted','La configuration du forfait est appliquée automatiquement et reste verrouillée jusqu’à épuisement du quota.':'The package configuration is applied automatically and remains locked until all sessions have been used.','séance(s) restante(s)':'session(s) remaining',
  'Forfait':'Package','Restantes':'Remaining','Ajouter un cours':'Add a lesson','Retirer un cours':'Remove a lesson','Réduire le package':'Decrease package','Augmenter le package':'Increase package','Enregistrer le package':'Save package','Nombre de cours du package':'Number of lessons in package','Modifier le cours':'Edit lesson','Modifier le cours communautaire':'Edit community lesson','Cours modifié':'Lesson updated','Modifier le logo':'Change logo','Choisir une image':'Choose an image','Logo de l’académie mis à jour':'Academy logo updated','PNG, JPEG ou WebP, 2 Mo maximum.':'PNG, JPEG or WebP, maximum 2 MB.','Le logo doit être une image PNG, JPEG ou WebP de 2 Mo maximum.':'The logo must be a PNG, JPEG or WebP image no larger than 2 MB.','Supprimer le joueur':'Delete player','Supprimer le joueur ?':'Delete player?','Ce joueur sera masqué de toutes les listes sans supprimer définitivement ses données.':'This player will be hidden from all lists without permanently deleting their data.','Supprimer la communauté':'Delete community','Supprimer le cours':'Delete lesson','Supprimer la communauté ?':'Delete community?','Supprimer le cours ?':'Delete lesson?','La communauté et tous ses cours seront masqués sans suppression définitive des données.':'The community and all its lessons will be hidden without permanently deleting their data.','Ce cours sera masqué sans suppression définitive de ses données.':'This lesson will be hidden without permanently deleting its data.','Communauté supprimée':'Community deleted','Cours supprimé':'Lesson deleted','Cours':'Lesson','Cours de tennis':'Tennis lesson','Administrateur':'Administrator','admin':'Administrator','root':'Root administrator','academy_manager':'Academy manager','booking_manager':'Booking manager','ID':'ID',
  'Lucas a fait une très belle séance aujourd’hui.':'Lucas had a great session today.','Merci pour les photos !':'Thank you for the photos!','Parents · Groupe U10':'Parents · U10 group','Sophie : Je peux apporter les boissons.':'Sophie: I can bring the drinks.','Hier':'Yesterday','Le compte-rendu est disponible.':'The session report is available.','Mme Ngono':'Mrs Ngono','Coach Émilie':'Coach Émilie',
  '22–23 août':'22–23 August','05–07 sept.':'5–7 September','19 sept.':'19 September','Compétition U8–U12':'U8–U12 competition','Initiation & technique':'Beginners & technique','Préparation physique':'Fitness training','Performance U14':'U14 performance',
  'Membre de la famille':'Family member','Authentification requise.':'Authentication required.','Permission insuffisante.':'You do not have permission to perform this action.','Académie non autorisée.':'You are not authorised to manage this academy.','Administrateur introuvable.':'Administrator not found.','Profil administrateur introuvable.':'Administrator profile not found.','Compte administrateur suspendu.':'Administrator account suspended.','Compte coach actif requis.':'An active coach account is required.','Profil utilisateur inactif.':'User profile is inactive.',
  'Aucune configuration de séance ne correspond à l’âge de ce joueur.':'No session configuration matches this player’s age.','Capacité incompatible avec le type de séance.':'The capacity is not compatible with this session type.','Capacité invalide.':'Invalid capacity.','Configuration absente ou inactive.':'The configuration is missing or inactive.','Configuration introuvable.':'Configuration not found.','Cette configuration de séance ne correspond pas à l’âge du joueur.':'This session configuration does not match the player’s age.','Cette configuration de séance n’est plus disponible.':'This session configuration is no longer available.','Cette configuration chevauche une tranche d’âge existante.':'This configuration overlaps an existing age range.','Plusieurs configurations se chevauchent pour cet âge. Corrigez le catalogue.':'Several configurations overlap for this age. Please correct the catalogue.','Tranche d’âge invalide.':'Invalid age range.','Type de séance invalide.':'Invalid session type.','Prix invalide.':'Invalid price.','Devise invalide.':'Invalid currency.','Le nombre de séances doit être compris entre 1 et 1000.':'The number of sessions must be between 1 and 1,000.',
  'Joueur introuvable.':'Player not found.','Séance ou joueur introuvable.':'Session or player not found.','Ce joueur ne vous est pas rattaché.':'This player is not assigned to you.','Ce profil joueur est en attente de confirmation du paiement cash par un administrateur.':'This player profile is awaiting cash payment confirmation by an administrator.','Ce joueur n’a pas choisi le paiement cash.':'This player did not select cash payment.','Ce paiement cash ne peut pas être confirmé dans son état actuel.':'This cash payment cannot be confirmed in its current state.','Le forfait de ce joueur est épuisé. Demandez son réabonnement.':'This player’s package has run out. Please ask them to renew.','Le forfait de ce joueur est épuisé. Veuillez le réabonner.':'This player’s package has run out. Please renew it.','Choisissez un mode de paiement.':'Select a payment method.','Mode de paiement invalide.':'Invalid payment method.','Choisissez un type de séance.':'Select a session type.','Le nom et le prénom de l’enfant sont requis.':'The player’s first and last names are required.','Nom ou prénom invalide.':'Invalid first or last name.','Sexe invalide.':'Invalid gender.','L’âge doit être compris entre 3 et 80 ans.':'Age must be between 3 and 80.','L’âge du joueur doit être renseigné avant la réservation.':'The player’s age must be provided before booking.',
  'Réservation introuvable.':'Booking not found.','Cette réservation a déjà été traitée.':'This booking has already been processed.','Cette réservation ne peut plus être annulée.':'This booking can no longer be cancelled.','Cette réservation ne vous est pas assignée.':'This booking is not assigned to you.','La réservation doit être confirmée.':'The booking must be confirmed.','Décision invalide.':'Invalid decision.','Transition de statut interdite.':'This status change is not allowed.','Cette séance est complète.':'This session is full.','Cette séance ne peut plus être réservée.':'This session can no longer be booked.','Cette séance ne fait pas partie du forfait de ce joueur.':'This session is not included in this player’s package.','Cette séance n’est liée à aucune configuration valide.':'This session is not linked to a valid configuration.','La séance est complète ou fermée.':'The session is full or closed.','La configuration de cette séance est absente ou incompatible.':'This session’s configuration is missing or incompatible.','La configuration de cette séance ne correspond pas à l’âge du joueur.':'This session’s configuration does not match the player’s age.',
  'Ce cours ne correspond pas à la communauté du joueur.':'This course does not belong to the player’s community.','Communauté absente ou inactive.':'The community is missing or inactive.','Communauté introuvable.':'Community not found.','Une communauté porte déjà ce nom.':'A community with this name already exists.','Choisissez un utilisateur parent ou élève actif.':'Select an active parent or student user.','Un profil parent ou élève actif est requis.':'An active parent or student profile is required.','Cette adresse e-mail possède déjà un compte.':'An account already exists for this email address.','E-mail invalide.':'Invalid email address.','Nom invalide.':'Invalid name.','Description trop longue.':'The description is too long.','Commentaire trop long.':'The comment is too long.',
  'Coach incompatible avec cette configuration.':'The coach is not compatible with this configuration.','Stade ou terrain incompatible avec cette configuration.':'The venue or court is not compatible with this configuration.','Ce terrain est déjà occupé pendant cette période.':'This court is already booked during this period.','Choisissez un stade avant le numéro de terrain.':'Select a venue before entering a court number.','Nombre de terrains invalide.':'Invalid number of courts.','Terrain invalide.':'Invalid court.','Période invalide.':'Invalid period.','La période doit être comprise entre 1 et 31 jours.':'The period must be between 1 and 31 days.','La séance doit avoir commencé.':'The session must have started.','La séance doit avoir commencé avant son évaluation.':'The session must have started before it can be evaluated.','Confirmez la présence ou l’absence du joueur.':'Confirm whether the player attended or was absent.','Les heures d’arrivée et de départ sont invalides.':'The arrival and departure times are invalid.','Chaque note doit être comprise entre 1 et 5.':'Each rating must be between 1 and 5.','Langue invalide.':'Invalid language.','Rôle invalide.':'Invalid role.','Statut invalide.':'Invalid status.','Visibilité invalide.':'Invalid visibility.','Type de compte invalide.':'Invalid account type.','Session invalide.':'Invalid session.','Vous ne pouvez pas suspendre votre propre compte.':'You cannot suspend your own account.','Le rôle root est protégé.':'The root role is protected.','Seul le root peut créer un administrateur global.':'Only the root administrator can create a global administrator.','Seul le root peut gérer un administrateur global.':'Only the root administrator can manage a global administrator.','Un compte root ne peut pas être créé depuis l’application.':'A root account cannot be created from the application.',
  'Le package ne peut pas être inférieur au nombre de cours déjà consommés.':'The package cannot be lower than the number of lessons already used.','Le nombre de cours du package doit être un entier compris entre 0 et 10000.':'The package lesson count must be a whole number between 0 and 10,000.',
  'Cette séance est réservée aux joueurs de':'This session is for players aged','ans.':'years old.',
  'Navigation joueurs et familles':'Players and families navigation','Rechercher et sélectionner des joueurs':'Search and select players','Sélectionnez d’abord un joueur pour charger son package.':'Select a player first to load their package.','Les joueurs ayant un forfait pour le même sport et type de séance peuvent être ajoutés, quels que soient leur âge et leur communauté.':'Players with a package for the same sport and session type can be added, regardless of age or community.','Tous les joueurs peuvent être ajoutés à cette réservation.':'All players can be added to this booking.', 'Cours de la communauté (facultatif)':'Community course (optional)', 'La réservation sera confirmée immédiatement.':'The booking will be confirmed immediately.', 'Créer les réservations':'Create bookings',
  'Modifier le montant total':'Edit total amount','Montant total':'Total amount','Paiements en espèces en attente':'Pending cash payments', 'Aucun paiement en espèces en attente.':'No pending cash payments.', 'Montant du forfait à vérifier':'Package amount to verify', 'Impossible de charger les paiements en espèces.':'Unable to load cash payments.', 'Impossible de charger le montant partagé. Veuillez actualiser la page.':'Unable to load the shared amount. Please refresh the page.', 'Montant invalide.':'Invalid amount.',
  'Modifier le tournoi':'Edit tournament','Tournoi modifié':'Tournament updated','Tournoi supprimé':'Tournament deleted','Supprimer ce tournoi ?':'Delete this tournament?',
}
function translate(value:string, language:Language) {
  if (language === 'fr') return value
  if (english[value]) return english[value]
  let result=value
  for (const [fr,en] of Object.entries(english).sort((a,b)=>b[0].length-a[0].length)) result=result.replaceAll(fr,en)
  return result
}
type I18nValue={language:Language;setLanguage:(language:Language)=>void;t:(value:string)=>string}
const I18nContext=createContext<I18nValue>({language:'fr',setLanguage:()=>undefined,t:(value:string)=>value})
const detectLanguage = (): Language => {
  const saved = localStorage.getItem('classcard-language') ?? sessionStorage.getItem('classcard-language')
  if (saved === 'fr' || saved === 'en') return saved
  const browserLanguages = navigator.languages?.length ? navigator.languages : [navigator.language]
  return browserLanguages.some(value => value.toLowerCase().startsWith('fr')) ? 'fr' : 'en'
}
export function I18nProvider({children}:{children:ReactNode}) {
  const [language,setLanguageState]=useState<Language>(detectLanguage)
  const setLanguage=useCallback((value:Language)=>{localStorage.setItem('classcard-language',value);sessionStorage.removeItem('classcard-language');setLanguageState(value)},[])
  useEffect(()=>{document.documentElement.lang=language},[language])
  const value=useMemo(()=>({language,setLanguage,t:(text:string)=>translate(text,language)}),[language,setLanguage])
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>
}
export const useI18n=()=>useContext(I18nContext)
export const localeFor = (language: Language) => language === 'fr' ? 'fr-FR' : 'en-GB'
export const formatMoney = (value: number, currency: string, language: Language) => new Intl.NumberFormat(localeFor(language), { style: 'currency', currency, maximumFractionDigits: currency === 'XAF' ? 0 : 2 }).format(value)
